@SearchService_HostAddress = http://localhost:7002
@DevTunnel_Yarp = https://6fjddmjf-8090.jpe1.devtunnels.ms

GET {{SearchService_HostAddress}}/Search/?query="[Aspire]
Accept: application/json

###
GET {{SearchService_HostAddress}}/search/similar-titles?query=Aspire
Accept: application/json

###
GET {{DevTunnel_Yarp}}/search/similar-titles?query=Aspire
Accept: application/json
