// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TreeGraph.Api.NodeEavSky.Data;

#nullable disable

namespace TreeGraph.Api.NodeEavSky.Data.Migrations
{
    [DbContext(typeof(TreeGraphDbContext))]
    [Migration("20261006131020_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.AttributeAuditLog", b =>
                {
                    b.Property<string>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("audit_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<string>("AttributeId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("attribute_id");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("attribute_name");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("change_type");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("changed_by");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_ip");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.HasKey("AuditId");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("ix_audit_time");

                    b.HasIndex("EntityType", "EntityId", "ChangedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_entity");

                    b.ToTable("attribute_audit_log", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.AttributeDefinition", b =>
                {
                    b.Property<string>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("attribute_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<JsonDocument>("AllowedValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_values");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("attribute_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_value");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_searchable");

                    b.Property<bool>("IsSortable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sortable");

                    b.Property<string>("RefCompositeTypeId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ref_composite_type_id");

                    b.Property<string>("RefOptionSetId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ref_option_set_id");

                    b.Property<string>("RefTableDefinitionId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ref_table_definition_id");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<JsonDocument>("ValidationRule")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_rule");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("AttributeId");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_attr_catalog_entity")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("RefCompositeTypeId");

                    b.HasIndex("RefOptionSetId");

                    b.HasIndex("RefTableDefinitionId");

                    b.HasIndex("UnitId");

                    b.HasIndex("EntityType", "AttributeName")
                        .IsUnique()
                        .HasDatabaseName("uq_attr_catalog");

                    b.ToTable("attribute_catalog", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.AttributeValue", b =>
                {
                    b.Property<string>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("value_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<string>("AttributeId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("attribute_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("boolean")
                        .HasColumnName("value_bool");

                    b.Property<DateOnly?>("ValueDateOnly")
                        .HasColumnType("date")
                        .HasColumnName("value_dateonly");

                    b.Property<DateTimeOffset?>("ValueDatetime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("value_datetime");

                    b.Property<decimal?>("ValueDecimal")
                        .HasPrecision(38, 15)
                        .HasColumnType("numeric(38,15)")
                        .HasColumnName("value_decimal");

                    b.Property<JsonDocument>("ValueFileMeta")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_file_meta");

                    b.Property<long?>("ValueInt")
                        .HasColumnType("bigint")
                        .HasColumnName("value_int");

                    b.Property<JsonDocument>("ValueJsonb")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_jsonb");

                    b.Property<string>("ValueString")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value_string");

                    b.Property<TimeOnly?>("ValueTime")
                        .HasColumnType("time(0)")
                        .HasColumnName("value_time");

                    b.HasKey("ValueId");

                    b.HasIndex("UnitId");

                    b.HasIndex("ValueFileMeta")
                        .HasDatabaseName("ix_av_file_meta")
                        .HasFilter("value_file_meta IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ValueFileMeta"), "GIN");

                    b.HasIndex("ValueJsonb")
                        .HasDatabaseName("ix_av_jsonb")
                        .HasFilter("value_jsonb IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ValueJsonb"), "GIN");

                    b.HasIndex("AttributeId", "ValueBool")
                        .HasDatabaseName("ix_av_attr_bool")
                        .HasFilter("value_bool IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueDateOnly")
                        .HasDatabaseName("ix_av_attr_dateonly")
                        .HasFilter("value_dateonly IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueDatetime")
                        .HasDatabaseName("ix_av_attr_datetime")
                        .HasFilter("value_datetime IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueDecimal")
                        .HasDatabaseName("ix_av_attr_decimal")
                        .HasFilter("value_decimal IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueInt")
                        .HasDatabaseName("ix_av_attr_int")
                        .HasFilter("value_int IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueString")
                        .HasDatabaseName("ix_av_attr_string")
                        .HasFilter("value_string IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueTime")
                        .HasDatabaseName("ix_av_attr_time")
                        .HasFilter("value_time IS NOT NULL");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_av_entity");

                    b.HasIndex("EntityId", "EntityType", "AttributeId")
                        .IsUnique()
                        .HasDatabaseName("uq_av_entity_attr");

                    b.HasIndex("EntityType", "EntityId", "UpdatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_av_entity_updated");

                    b.ToTable("attribute_values", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CompositeFieldDefinition", b =>
                {
                    b.Property<string>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("field_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<JsonDocument>("AllowedValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_values");

                    b.Property<string>("CompositeTypeId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("composite_type_id");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_value");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_name");

                    b.Property<bool>("IsArray")
                        .HasColumnType("boolean")
                        .HasColumnName("is_array");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_searchable");

                    b.Property<bool>("IsSortable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sortable");

                    b.Property<string>("RefCompositeTypeId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ref_composite_type_id");

                    b.Property<string>("RefOptionSetId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ref_option_set_id");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<JsonDocument>("ValidationRule")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_rule");

                    b.HasKey("FieldId");

                    b.HasIndex("RefCompositeTypeId");

                    b.HasIndex("RefOptionSetId");

                    b.HasIndex("UnitId");

                    b.HasIndex("CompositeTypeId", "FieldName")
                        .IsUnique()
                        .HasDatabaseName("uq_composite_field");

                    b.ToTable("composite_field_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_composite_field_decimal_unit", "data_type = 'decimal' OR unit_id IS NULL");

                            t.HasCheckConstraint("ck_composite_field_single_choice_optionset", "data_type = 'single_choice' OR ref_option_set_id IS NULL");
                        });
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CompositeTypeDefinition", b =>
                {
                    b.Property<string>("CompositeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("composite_type_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("CompositeTypeId");

                    b.HasIndex("EntityType", "TypeName", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_composite_type");

                    b.ToTable("composite_type_definitions", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CustomTableColumn", b =>
                {
                    b.Property<string>("ColumnId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("column_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<JsonDocument>("AllowedValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_values");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("column_name");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_value");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_searchable");

                    b.Property<bool>("IsSortable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sortable");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unique");

                    b.Property<string>("RefCompositeTypeId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ref_composite_type_id");

                    b.Property<string>("TableDefinitionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("table_definition_id");

                    b.Property<JsonDocument>("ValidationRule")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_rule");

                    b.HasKey("ColumnId");

                    b.HasIndex("RefCompositeTypeId");

                    b.HasIndex("TableDefinitionId", "ColumnName")
                        .IsUnique()
                        .HasDatabaseName("uq_custom_table_column");

                    b.ToTable("custom_table_columns", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CustomTableDefinition", b =>
                {
                    b.Property<string>("TableDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("table_definition_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("table_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("TableDefinitionId");

                    b.HasIndex("EntityType", "TableName", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_custom_table");

                    b.ToTable("custom_table_definitions", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CustomTableRow", b =>
                {
                    b.Property<string>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("row_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<string>("AttributeId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("attribute_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ParentEntityId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("parent_entity_id");

                    b.Property<string>("ParentEntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_entity_type");

                    b.Property<JsonDocument>("RowData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("row_data");

                    b.Property<int>("RowOrder")
                        .HasColumnType("integer")
                        .HasColumnName("row_order");

                    b.Property<string>("TableDefinitionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("table_definition_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RowId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("RowData")
                        .HasDatabaseName("ix_ctr_rowdata");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RowData"), "GIN");

                    b.HasIndex("TableDefinitionId")
                        .HasDatabaseName("ix_ctr_table");

                    b.HasIndex("ParentEntityId", "AttributeId", "RowOrder")
                        .HasDatabaseName("ix_ctr_order");

                    b.HasIndex("ParentEntityType", "ParentEntityId", "AttributeId")
                        .HasDatabaseName("ix_ctr_parent");

                    b.ToTable("custom_table_rows", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.EntityTypeDefinition", b =>
                {
                    b.Property<string>("EntityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("entity_type_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EntityTypeId");

                    b.HasIndex("EntityType")
                        .IsUnique()
                        .HasDatabaseName("uq_entity_type")
                        .HasFilter("is_deleted = false");

                    b.ToTable("entity_type_catalog", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.InodeEntity", b =>
                {
                    b.Property<string>("InodeId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("inode_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("AttachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attached_at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("entity_id");

                    b.HasKey("InodeId", "EntityType");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_inode_entity_entity");

                    b.HasIndex("InodeId")
                        .HasDatabaseName("ix_inode_entity_inode");

                    b.HasIndex("EntityType", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("uq_inode_entity_global");

                    b.ToTable("inode_entity", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.InodeEntityType", b =>
                {
                    b.Property<string>("InodeId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("inode_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("AttachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attached_at");

                    b.HasKey("InodeId", "EntityType");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_inode_et_type");

                    b.HasIndex("InodeId")
                        .HasDatabaseName("ix_inode_et_inode");

                    b.ToTable("inode_entitytype", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.OptionItem", b =>
                {
                    b.Property<string>("OptionItemId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("option_item_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<string>("OptionSetId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("option_set_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("OptionItemId");

                    b.HasIndex("OptionSetId")
                        .HasDatabaseName("ix_option_items_set");

                    b.HasIndex("OptionSetId", "Value")
                        .IsUnique()
                        .HasDatabaseName("uq_option_item_value");

                    b.ToTable("option_items", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.OptionSet", b =>
                {
                    b.Property<string>("OptionSetId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("option_set_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("set_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("OptionSetId");

                    b.HasIndex("EntityType", "SetName")
                        .IsUnique()
                        .HasDatabaseName("uq_option_set")
                        .HasFilter("is_deleted = false");

                    b.ToTable("option_sets", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_base_unit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("ToBaseFactor")
                        .HasPrecision(38, 15)
                        .HasColumnType("numeric(38,15)")
                        .HasColumnName("to_base_factor");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .IsUnique()
                        .HasDatabaseName("uq_unit_category_base")
                        .HasFilter("is_base_unit = true");

                    b.HasIndex("Category", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_unit_category_name");

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.StringTreeSky.Entities.StringNodeEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("ParentId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_string_tree_sky_nodes_parent");

                    b.HasIndex("ParentId", "SortOrder")
                        .HasDatabaseName("ix_string_tree_sky_nodes_parent_sort");

                    b.ToTable("string_tree_sky_nodes", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Blazor.Shared.Trees.TreeSky.Models.StringTreeNode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<bool>("CanHaveChildren")
                        .HasColumnType("boolean")
                        .HasColumnName("can_have_children");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("ParentId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_string_tree_nodes_parent_id");

                    b.ToTable("string_tree_nodes", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.AttributeDefinition", b =>
                {
                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.CompositeTypeDefinition", "RefCompositeType")
                        .WithMany()
                        .HasForeignKey("RefCompositeTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.OptionSet", "RefOptionSet")
                        .WithMany()
                        .HasForeignKey("RefOptionSetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.CustomTableDefinition", "RefTableDefinition")
                        .WithMany()
                        .HasForeignKey("RefTableDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RefCompositeType");

                    b.Navigation("RefOptionSet");

                    b.Navigation("RefTableDefinition");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.AttributeValue", b =>
                {
                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.AttributeDefinition", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Attribute");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CompositeFieldDefinition", b =>
                {
                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.CompositeTypeDefinition", "CompositeType")
                        .WithMany("Fields")
                        .HasForeignKey("CompositeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.CompositeTypeDefinition", "RefCompositeType")
                        .WithMany()
                        .HasForeignKey("RefCompositeTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.OptionSet", "RefOptionSet")
                        .WithMany()
                        .HasForeignKey("RefOptionSetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompositeType");

                    b.Navigation("RefCompositeType");

                    b.Navigation("RefOptionSet");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CustomTableColumn", b =>
                {
                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.CompositeTypeDefinition", "RefCompositeType")
                        .WithMany()
                        .HasForeignKey("RefCompositeTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.CustomTableDefinition", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RefCompositeType");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CustomTableRow", b =>
                {
                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.AttributeDefinition", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.CustomTableDefinition", "Table")
                        .WithMany()
                        .HasForeignKey("TableDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.OptionItem", b =>
                {
                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.OptionSet", "OptionSet")
                        .WithMany("Items")
                        .HasForeignKey("OptionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionSet");
                });

            modelBuilder.Entity("TreeGraph.Api.StringTreeSky.Entities.StringNodeEntity", b =>
                {
                    b.HasOne("TreeGraph.Api.StringTreeSky.Entities.StringNodeEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CompositeTypeDefinition", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CustomTableDefinition", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.OptionSet", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TreeGraph.Api.StringTreeSky.Entities.StringNodeEntity", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
