// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TreeGraph.Api.Data;

#nullable disable

namespace TreeGraph.Api.Data.Migrations
{
    [DbContext(typeof(EavDbContext))]
    partial class EavDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TreeGraph.Api.Entities.AttributeAuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("AuditId"));

                    b.Property<long>("AttributeId")
                        .HasColumnType("bigint")
                        .HasColumnName("attribute_id");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("attribute_name");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("change_type");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("changed_by");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_ip");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.HasKey("AuditId");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("ix_audit_time");

                    b.HasIndex("EntityType", "EntityId", "ChangedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_entity");

                    b.ToTable("attribute_audit_log", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.AttributeDefinition", b =>
                {
                    b.Property<long>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("attribute_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("AttributeId"));

                    b.Property<JsonDocument>("AllowedValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_values");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("attribute_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_value");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsMultiValue")
                        .HasColumnType("boolean")
                        .HasColumnName("is_multi_value");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_searchable");

                    b.Property<bool>("IsSortable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sortable");

                    b.Property<long?>("RefCompositeTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("ref_composite_type_id");

                    b.Property<long?>("RefOptionSetId")
                        .HasColumnType("bigint")
                        .HasColumnName("ref_option_set_id");

                    b.Property<long?>("RefTableDefinitionId")
                        .HasColumnType("bigint")
                        .HasColumnName("ref_table_definition_id");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<JsonDocument>("ValidationRule")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_rule");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("AttributeId");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_attr_catalog_entity")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("RefCompositeTypeId");

                    b.HasIndex("RefOptionSetId");

                    b.HasIndex("RefTableDefinitionId");

                    b.HasIndex("UnitId");

                    b.HasIndex("EntityType", "AttributeName")
                        .IsUnique()
                        .HasDatabaseName("uq_attr_catalog");

                    b.ToTable("attribute_catalog", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.AttributeValue", b =>
                {
                    b.Property<long>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("value_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("ValueId"));

                    b.Property<long>("AttributeId")
                        .HasColumnType("bigint")
                        .HasColumnName("attribute_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("boolean")
                        .HasColumnName("value_bool");

                    b.Property<DateOnly?>("ValueDateOnly")
                        .HasColumnType("date")
                        .HasColumnName("value_dateonly");

                    b.Property<DateTimeOffset?>("ValueDatetime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("value_datetime");

                    b.Property<decimal?>("ValueDecimal")
                        .HasPrecision(38, 15)
                        .HasColumnType("numeric(38,15)")
                        .HasColumnName("value_decimal");

                    b.Property<JsonDocument>("ValueFileMeta")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_file_meta");

                    b.Property<long?>("ValueInt")
                        .HasColumnType("bigint")
                        .HasColumnName("value_int");

                    b.Property<JsonDocument>("ValueJsonb")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_jsonb");

                    b.Property<string>("ValueString")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value_string");

                    b.Property<TimeOnly?>("ValueTime")
                        .HasColumnType("time(0)")
                        .HasColumnName("value_time");

                    b.HasKey("ValueId");

                    b.HasIndex("UnitId");

                    b.HasIndex("ValueFileMeta")
                        .HasDatabaseName("ix_av_file_meta")
                        .HasFilter("value_file_meta IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ValueFileMeta"), "GIN");

                    b.HasIndex("ValueJsonb")
                        .HasDatabaseName("ix_av_jsonb")
                        .HasFilter("value_jsonb IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ValueJsonb"), "GIN");

                    b.HasIndex("AttributeId", "ValueBool")
                        .HasDatabaseName("ix_av_attr_bool")
                        .HasFilter("value_bool IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueDateOnly")
                        .HasDatabaseName("ix_av_attr_dateonly")
                        .HasFilter("value_dateonly IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueDatetime")
                        .HasDatabaseName("ix_av_attr_datetime")
                        .HasFilter("value_datetime IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueDecimal")
                        .HasDatabaseName("ix_av_attr_decimal")
                        .HasFilter("value_decimal IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueInt")
                        .HasDatabaseName("ix_av_attr_int")
                        .HasFilter("value_int IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueString")
                        .HasDatabaseName("ix_av_attr_string")
                        .HasFilter("value_string IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueTime")
                        .HasDatabaseName("ix_av_attr_time")
                        .HasFilter("value_time IS NOT NULL");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_av_entity");

                    b.HasIndex("EntityId", "EntityType", "AttributeId")
                        .IsUnique()
                        .HasDatabaseName("uq_av_entity_attr");

                    b.ToTable("attribute_values", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.CompositeFieldDefinition", b =>
                {
                    b.Property<long>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("field_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("FieldId"));

                    b.Property<JsonDocument>("AllowedValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_values");

                    b.Property<long>("CompositeTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("composite_type_id");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_value");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_name");

                    b.Property<bool>("IsArray")
                        .HasColumnType("boolean")
                        .HasColumnName("is_array");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_searchable");

                    b.Property<bool>("IsSortable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sortable");

                    b.Property<long?>("RefCompositeTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("ref_composite_type_id");

                    b.Property<JsonDocument>("ValidationRule")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_rule");

                    b.HasKey("FieldId");

                    b.HasIndex("RefCompositeTypeId");

                    b.HasIndex("CompositeTypeId", "FieldName")
                        .IsUnique()
                        .HasDatabaseName("uq_composite_field");

                    b.ToTable("composite_field_definitions", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.CompositeTypeDefinition", b =>
                {
                    b.Property<long>("CompositeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("composite_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CompositeTypeId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("CompositeTypeId");

                    b.HasIndex("EntityType", "TypeName", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_composite_type");

                    b.ToTable("composite_type_definitions", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.CustomTableColumn", b =>
                {
                    b.Property<long>("ColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("column_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("ColumnId"));

                    b.Property<JsonDocument>("AllowedValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_values");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("column_name");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_value");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_searchable");

                    b.Property<bool>("IsSortable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sortable");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unique");

                    b.Property<long?>("RefCompositeTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("ref_composite_type_id");

                    b.Property<long>("TableDefinitionId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_definition_id");

                    b.Property<JsonDocument>("ValidationRule")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_rule");

                    b.HasKey("ColumnId");

                    b.HasIndex("RefCompositeTypeId");

                    b.HasIndex("TableDefinitionId", "ColumnName")
                        .IsUnique()
                        .HasDatabaseName("uq_custom_table_column");

                    b.ToTable("custom_table_columns", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.CustomTableDefinition", b =>
                {
                    b.Property<long>("TableDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("table_definition_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("TableDefinitionId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("table_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("TableDefinitionId");

                    b.HasIndex("EntityType", "TableName", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_custom_table");

                    b.ToTable("custom_table_definitions", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.CustomTableRow", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("RowId"));

                    b.Property<long>("AttributeId")
                        .HasColumnType("bigint")
                        .HasColumnName("attribute_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("ParentEntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_entity_id");

                    b.Property<string>("ParentEntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_entity_type");

                    b.Property<JsonDocument>("RowData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("row_data");

                    b.Property<int>("RowOrder")
                        .HasColumnType("integer")
                        .HasColumnName("row_order");

                    b.Property<long>("TableDefinitionId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_definition_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RowId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("RowData")
                        .HasDatabaseName("ix_ctr_rowdata");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RowData"), "GIN");

                    b.HasIndex("TableDefinitionId")
                        .HasDatabaseName("ix_ctr_table");

                    b.HasIndex("ParentEntityId", "AttributeId", "RowOrder")
                        .HasDatabaseName("ix_ctr_order");

                    b.HasIndex("ParentEntityType", "ParentEntityId", "AttributeId")
                        .HasDatabaseName("ix_ctr_parent");

                    b.ToTable("custom_table_rows", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.OptionItem", b =>
                {
                    b.Property<long>("OptionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("option_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("OptionItemId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<long>("OptionSetId")
                        .HasColumnType("bigint")
                        .HasColumnName("option_set_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("OptionItemId");

                    b.HasIndex("OptionSetId")
                        .HasDatabaseName("ix_option_items_set");

                    b.HasIndex("OptionSetId", "Value")
                        .IsUnique()
                        .HasDatabaseName("uq_option_item_value");

                    b.ToTable("option_items", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.OptionSet", b =>
                {
                    b.Property<long>("OptionSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("option_set_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("OptionSetId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("set_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("OptionSetId");

                    b.HasIndex("EntityType", "SetName")
                        .IsUnique()
                        .HasDatabaseName("uq_option_set");

                    b.ToTable("option_sets", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_base_unit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("ToBaseFactor")
                        .HasPrecision(38, 15)
                        .HasColumnType("numeric(38,15)")
                        .HasColumnName("to_base_factor");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .IsUnique()
                        .HasDatabaseName("uq_unit_category_base")
                        .HasFilter("is_base_unit = true");

                    b.HasIndex("Category", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_unit_category_name");

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.AttributeDefinition", b =>
                {
                    b.HasOne("TreeGraph.Api.Entities.CompositeTypeDefinition", "RefCompositeType")
                        .WithMany()
                        .HasForeignKey("RefCompositeTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.Entities.OptionSet", "RefOptionSet")
                        .WithMany()
                        .HasForeignKey("RefOptionSetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.Entities.CustomTableDefinition", "RefTableDefinition")
                        .WithMany()
                        .HasForeignKey("RefTableDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RefCompositeType");

                    b.Navigation("RefOptionSet");

                    b.Navigation("RefTableDefinition");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.AttributeValue", b =>
                {
                    b.HasOne("TreeGraph.Api.Entities.AttributeDefinition", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TreeGraph.Api.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Attribute");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.CompositeFieldDefinition", b =>
                {
                    b.HasOne("TreeGraph.Api.Entities.CompositeTypeDefinition", "CompositeType")
                        .WithMany("Fields")
                        .HasForeignKey("CompositeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreeGraph.Api.Entities.CompositeTypeDefinition", "RefCompositeType")
                        .WithMany()
                        .HasForeignKey("RefCompositeTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompositeType");

                    b.Navigation("RefCompositeType");
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.CustomTableColumn", b =>
                {
                    b.HasOne("TreeGraph.Api.Entities.CompositeTypeDefinition", "RefCompositeType")
                        .WithMany()
                        .HasForeignKey("RefCompositeTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.Entities.CustomTableDefinition", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RefCompositeType");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.CustomTableRow", b =>
                {
                    b.HasOne("TreeGraph.Api.Entities.AttributeDefinition", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreeGraph.Api.Entities.CustomTableDefinition", "Table")
                        .WithMany()
                        .HasForeignKey("TableDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.OptionItem", b =>
                {
                    b.HasOne("TreeGraph.Api.Entities.OptionSet", "OptionSet")
                        .WithMany("Items")
                        .HasForeignKey("OptionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionSet");
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.CompositeTypeDefinition", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.CustomTableDefinition", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("TreeGraph.Api.Entities.OptionSet", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
