// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TreeGraph.Api.Data;

#nullable disable

namespace TreeGraph.Api.Data.Migrations
{
    [DbContext(typeof(TreeGraphDbContext))]
    partial class TreeGraphDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.AttributeAuditLog", b =>
                {
                    b.Property<string>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("audit_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<string>("AttributeId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("attribute_id");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("attribute_name");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("change_type");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("changed_by");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_ip");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.HasKey("AuditId");

                    b.HasIndex("ChangedAt")
                        .HasDatabaseName("ix_audit_time");

                    b.HasIndex("EntityType", "EntityId", "ChangedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_entity");

                    b.ToTable("attribute_audit_log", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.AttributeDefinition", b =>
                {
                    b.Property<string>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("attribute_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<JsonDocument>("AllowedValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_values");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("attribute_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_value");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_searchable");

                    b.Property<bool>("IsSortable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sortable");

                    b.Property<string>("RefCompositeTypeId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ref_composite_type_id");

                    b.Property<string>("RefOptionSetId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ref_option_set_id");

                    b.Property<string>("RefTableDefinitionId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ref_table_definition_id");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<JsonDocument>("ValidationRule")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_rule");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("AttributeId");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_attr_catalog_entity")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("RefCompositeTypeId");

                    b.HasIndex("RefOptionSetId");

                    b.HasIndex("RefTableDefinitionId");

                    b.HasIndex("UnitId");

                    b.HasIndex("EntityType", "AttributeName")
                        .IsUnique()
                        .HasDatabaseName("uq_attr_catalog");

                    b.ToTable("attribute_catalog", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.AttributeValue", b =>
                {
                    b.Property<string>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("value_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<string>("AttributeId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("attribute_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("boolean")
                        .HasColumnName("value_bool");

                    b.Property<DateOnly?>("ValueDateOnly")
                        .HasColumnType("date")
                        .HasColumnName("value_dateonly");

                    b.Property<DateTimeOffset?>("ValueDatetime")
                        .HasColumnType("timestamptz")
                        .HasColumnName("value_datetime");

                    b.Property<decimal?>("ValueDecimal")
                        .HasPrecision(38, 15)
                        .HasColumnType("numeric(38,15)")
                        .HasColumnName("value_decimal");

                    b.Property<JsonDocument>("ValueFileMeta")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_file_meta");

                    b.Property<long?>("ValueInt")
                        .HasColumnType("bigint")
                        .HasColumnName("value_int");

                    b.Property<JsonDocument>("ValueJsonb")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_jsonb");

                    b.Property<string>("ValueString")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value_string");

                    b.Property<TimeOnly?>("ValueTime")
                        .HasColumnType("time(0)")
                        .HasColumnName("value_time");

                    b.HasKey("ValueId");

                    b.HasIndex("UnitId");

                    b.HasIndex("ValueFileMeta")
                        .HasDatabaseName("ix_av_file_meta")
                        .HasFilter("value_file_meta IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ValueFileMeta"), "GIN");

                    b.HasIndex("ValueJsonb")
                        .HasDatabaseName("ix_av_jsonb")
                        .HasFilter("value_jsonb IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ValueJsonb"), "GIN");

                    b.HasIndex("AttributeId", "ValueBool")
                        .HasDatabaseName("ix_av_attr_bool")
                        .HasFilter("value_bool IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueDateOnly")
                        .HasDatabaseName("ix_av_attr_dateonly")
                        .HasFilter("value_dateonly IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueDatetime")
                        .HasDatabaseName("ix_av_attr_datetime")
                        .HasFilter("value_datetime IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueDecimal")
                        .HasDatabaseName("ix_av_attr_decimal")
                        .HasFilter("value_decimal IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueInt")
                        .HasDatabaseName("ix_av_attr_int")
                        .HasFilter("value_int IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueString")
                        .HasDatabaseName("ix_av_attr_string")
                        .HasFilter("value_string IS NOT NULL");

                    b.HasIndex("AttributeId", "ValueTime")
                        .HasDatabaseName("ix_av_attr_time")
                        .HasFilter("value_time IS NOT NULL");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_av_entity");

                    b.HasIndex("EntityId", "EntityType", "AttributeId")
                        .IsUnique()
                        .HasDatabaseName("uq_av_entity_attr");

                    b.HasIndex("EntityType", "EntityId", "UpdatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_av_entity_updated");

                    b.ToTable("attribute_values", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CompositeFieldDefinition", b =>
                {
                    b.Property<string>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("field_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<JsonDocument>("AllowedValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_values");

                    b.Property<string>("CompositeTypeId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("composite_type_id");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_value");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_name");

                    b.Property<bool>("IsArray")
                        .HasColumnType("boolean")
                        .HasColumnName("is_array");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_searchable");

                    b.Property<bool>("IsSortable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sortable");

                    b.Property<string>("RefCompositeTypeId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ref_composite_type_id");

                    b.Property<string>("RefOptionSetId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ref_option_set_id");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<JsonDocument>("ValidationRule")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_rule");

                    b.HasKey("FieldId");

                    b.HasIndex("RefCompositeTypeId");

                    b.HasIndex("RefOptionSetId");

                    b.HasIndex("UnitId");

                    b.HasIndex("CompositeTypeId", "FieldName")
                        .IsUnique()
                        .HasDatabaseName("uq_composite_field");

                    b.ToTable("composite_field_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_composite_field_decimal_unit", "data_type = 'decimal' OR unit_id IS NULL");

                            t.HasCheckConstraint("ck_composite_field_single_choice_optionset", "data_type = 'single_choice' OR ref_option_set_id IS NULL");
                        });
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CompositeTypeDefinition", b =>
                {
                    b.Property<string>("CompositeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("composite_type_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("CompositeTypeId");

                    b.HasIndex("EntityType", "TypeName", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_composite_type");

                    b.ToTable("composite_type_definitions", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CustomTableColumn", b =>
                {
                    b.Property<string>("ColumnId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("column_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<JsonDocument>("AllowedValues")
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_values");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("column_name");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("default_value");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_searchable");

                    b.Property<bool>("IsSortable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sortable");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unique");

                    b.Property<string>("RefCompositeTypeId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("ref_composite_type_id");

                    b.Property<string>("TableDefinitionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("table_definition_id");

                    b.Property<JsonDocument>("ValidationRule")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_rule");

                    b.HasKey("ColumnId");

                    b.HasIndex("RefCompositeTypeId");

                    b.HasIndex("TableDefinitionId", "ColumnName")
                        .IsUnique()
                        .HasDatabaseName("uq_custom_table_column");

                    b.ToTable("custom_table_columns", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CustomTableDefinition", b =>
                {
                    b.Property<string>("TableDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("table_definition_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("table_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("TableDefinitionId");

                    b.HasIndex("EntityType", "TableName", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_custom_table");

                    b.ToTable("custom_table_definitions", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CustomTableRow", b =>
                {
                    b.Property<string>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("row_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<string>("AttributeId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("attribute_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ParentEntityId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("parent_entity_id");

                    b.Property<string>("ParentEntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_entity_type");

                    b.Property<JsonDocument>("RowData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("row_data");

                    b.Property<int>("RowOrder")
                        .HasColumnType("integer")
                        .HasColumnName("row_order");

                    b.Property<string>("TableDefinitionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("table_definition_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RowId");

                    b.HasIndex("AttributeId");

                    b.HasIndex("RowData")
                        .HasDatabaseName("ix_ctr_rowdata");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RowData"), "GIN");

                    b.HasIndex("TableDefinitionId")
                        .HasDatabaseName("ix_ctr_table");

                    b.HasIndex("ParentEntityId", "AttributeId", "RowOrder")
                        .HasDatabaseName("ix_ctr_order");

                    b.HasIndex("ParentEntityType", "ParentEntityId", "AttributeId")
                        .HasDatabaseName("ix_ctr_parent");

                    b.ToTable("custom_table_rows", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.EntityTypeDefinition", b =>
                {
                    b.Property<string>("EntityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("entity_type_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EntityTypeId");

                    b.HasIndex("EntityType")
                        .IsUnique()
                        .HasDatabaseName("uq_entity_type")
                        .HasFilter("is_deleted = false");

                    b.ToTable("entity_type_catalog", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.InodeEntity", b =>
                {
                    b.Property<string>("InodeId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("inode_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("AttachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attached_at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("entity_id");

                    b.HasKey("InodeId", "EntityType");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_inode_entity_entity");

                    b.HasIndex("InodeId")
                        .HasDatabaseName("ix_inode_entity_inode");

                    b.HasIndex("EntityType", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("uq_inode_entity_global");

                    b.ToTable("inode_entity", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.InodeEntityType", b =>
                {
                    b.Property<string>("InodeId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("inode_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("AttachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attached_at");

                    b.HasKey("InodeId", "EntityType");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_inode_et_type");

                    b.HasIndex("InodeId")
                        .HasDatabaseName("ix_inode_et_inode");

                    b.ToTable("inode_entitytype", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.OptionItem", b =>
                {
                    b.Property<string>("OptionItemId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("option_item_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<string>("OptionSetId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("option_set_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("OptionItemId");

                    b.HasIndex("OptionSetId")
                        .HasDatabaseName("ix_option_items_set");

                    b.HasIndex("OptionSetId", "Value")
                        .IsUnique()
                        .HasDatabaseName("uq_option_item_value");

                    b.ToTable("option_items", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.OptionSet", b =>
                {
                    b.Property<string>("OptionSetId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("option_set_id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("set_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("OptionSetId");

                    b.HasIndex("EntityType", "SetName")
                        .IsUnique()
                        .HasDatabaseName("uq_option_set")
                        .HasFilter("is_deleted = false");

                    b.ToTable("option_sets", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("boolean")
                        .HasColumnName("is_base_unit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.Property<decimal>("ToBaseFactor")
                        .HasPrecision(38, 15)
                        .HasColumnType("numeric(38,15)")
                        .HasColumnName("to_base_factor");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .IsUnique()
                        .HasDatabaseName("uq_unit_category_base")
                        .HasFilter("is_base_unit = true");

                    b.HasIndex("Category", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_unit_category_name");

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Api.StringTreeSky.Entities.StringNodeEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()::text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasDefaultValue("StringTreeNode")
                        .HasColumnName("entity_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("ParentId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_string_tree_sky_nodes_entity_type");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_string_tree_sky_nodes_parent");

                    b.HasIndex("ParentId", "SortOrder")
                        .HasDatabaseName("ix_string_tree_sky_nodes_parent_sort");

                    b.ToTable("string_tree_sky_nodes", (string)null);
                });

            modelBuilder.Entity("TreeGraph.Shared.TreeSky.Entities.CategoryTree", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<bool>("CanHaveChildren")
                        .HasColumnType("boolean")
                        .HasColumnName("can_have_children");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("ParentId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_category_trees_parent");

                    b.ToTable("category_trees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            CanHaveChildren = false,
                            Description = "根分类示例",
                            IsArchived = false,
                            Name = "Sample Root",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "39EA6315-0A74-40F6-A096-8E15CCC98579",
                            CanHaveChildren = false,
                            Description = "子分类 1",
                            IsArchived = false,
                            Name = "Sample 1",
                            ParentId = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "C1EBEE10-97F6-44C8-9852-2F574515BF51",
                            CanHaveChildren = false,
                            Description = "子分类 1.1",
                            IsArchived = false,
                            Name = "Sample 1.1",
                            ParentId = "39EA6315-0A74-40F6-A096-8E15CCC98579",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "C8969ED0-C018-4FDC-AE55-C363BD95C853",
                            CanHaveChildren = false,
                            Description = "子分类 2",
                            IsArchived = false,
                            Name = "Sample 2",
                            ParentId = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "ED0990CF-5BB7-4C36-A3BB-3AF606AD1974",
                            CanHaveChildren = false,
                            Description = "子分类 2.1",
                            IsArchived = false,
                            Name = "Sample 2.1",
                            ParentId = "C8969ED0-C018-4FDC-AE55-C363BD95C853",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "975599CC-B967-4AD2-B4B8-9E00D889FB4D",
                            CanHaveChildren = false,
                            Description = "子分类 2.2 [Archived]",
                            IsArchived = true,
                            Name = "Sample 2.2",
                            ParentId = "C8969ED0-C018-4FDC-AE55-C363BD95C853",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            CanHaveChildren = false,
                            Description = "子分类 3",
                            IsArchived = false,
                            Name = "Sample 3",
                            ParentId = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "8E971C0E-B99A-4931-AFD6-46E44D6ECE5A",
                            CanHaveChildren = false,
                            Description = "子分类 3.1",
                            IsArchived = false,
                            Name = "Sample 3.1",
                            ParentId = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "5C30BACA-3C11-4677-8123-8EC2BE729667",
                            CanHaveChildren = false,
                            Description = "子分类 3.2",
                            IsArchived = false,
                            Name = "Sample 3.2",
                            ParentId = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "1B16336D-FB7F-42AA-AFD2-F78388883336",
                            CanHaveChildren = false,
                            Description = "子分类 3.3",
                            IsArchived = false,
                            Name = "Sample 3.3",
                            ParentId = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "35F02829-6490-467E-9D3E-C2EBF0EAA2B4",
                            CanHaveChildren = false,
                            Description = "子分类 3.3.1",
                            IsArchived = false,
                            Name = "Sample 3.3.1",
                            ParentId = "1B16336D-FB7F-42AA-AFD2-F78388883336",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("TreeGraph.Shared.TreeSky.Entities.UnitTree", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("abbreviation");

                    b.Property<bool>("CanHaveChildren")
                        .HasColumnType("boolean")
                        .HasColumnName("can_have_children");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("boolean")
                        .HasColumnName("has_children");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParentId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_unit_trees_parent");

                    b.ToTable("unit_trees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "",
                            HasChildren = true,
                            Name = "计量单位",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "货币计量单位",
                            HasChildren = true,
                            Name = "货币",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "长度计量单位",
                            HasChildren = true,
                            Name = "长度",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "质量计量单位",
                            HasChildren = true,
                            Name = "质量",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "时间计量单位",
                            HasChildren = true,
                            Name = "时间",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "温度计量单位",
                            HasChildren = true,
                            Name = "温度",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "电流计量单位",
                            HasChildren = true,
                            Name = "电流",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = "f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "电压计量单位",
                            HasChildren = true,
                            Name = "电压",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = "a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "功率计量单位",
                            HasChildren = true,
                            Name = "功率",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = "b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "面积计量单位",
                            HasChildren = true,
                            Name = "面积",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = "c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "体积计量单位",
                            HasChildren = true,
                            Name = "体积",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = "d0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "速度计量单位",
                            HasChildren = true,
                            Name = "速度",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = "e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "压力计量单位",
                            HasChildren = true,
                            Name = "压力",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = "f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "能量计量单位",
                            HasChildren = true,
                            Name = "能量",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = "a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "频率计量单位",
                            HasChildren = true,
                            Name = "频率",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = "b4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "角度计量单位",
                            HasChildren = true,
                            Name = "角度",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = "f7a8b9c0-d1e2-4f3a-4b5c-6d7e8f9a0b1c",
                            Abbreviation = "CNY",
                            CanHaveChildren = false,
                            Description = "人民币",
                            HasChildren = false,
                            Name = "元",
                            ParentId = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = "e6b7c8d9-f0a1-4b2c-3d4e-5f6a7b8c9d0e",
                            Abbreviation = "USD",
                            CanHaveChildren = false,
                            Description = "美元",
                            HasChildren = false,
                            Name = "美元",
                            ParentId = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = "d5c6d7e8-f9a0-4b1c-2d3e-4f5a6b7c8d9e",
                            Abbreviation = "EUR",
                            CanHaveChildren = false,
                            Description = "欧元",
                            HasChildren = false,
                            Name = "欧元",
                            ParentId = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = "c4d5e6f7-a8b9-4c0d-1e2f-3a4b5c6d7e8f",
                            Abbreviation = "GBP",
                            CanHaveChildren = false,
                            Description = "英镑",
                            HasChildren = false,
                            Name = "英镑",
                            ParentId = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            SortOrder = 18
                        },
                        new
                        {
                            Id = "b3c4d5e6-f7a8-4b9c-0d1e-2f3a4b5c6d7e",
                            Abbreviation = "JPY",
                            CanHaveChildren = false,
                            Description = "日元",
                            HasChildren = false,
                            Name = "日元",
                            ParentId = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            SortOrder = 19
                        },
                        new
                        {
                            Id = "a5b6c7d8-e9f0-4a1b-2c3d-4e5f6a7b8c9d",
                            Abbreviation = "HKD",
                            CanHaveChildren = false,
                            Description = "港元",
                            HasChildren = false,
                            Name = "港元",
                            ParentId = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = "b6c7d8e9-f0a1-4b2c-3d4e-5f6a7b8c9d0e",
                            Abbreviation = "AUD",
                            CanHaveChildren = false,
                            Description = "澳元",
                            HasChildren = false,
                            Name = "澳元",
                            ParentId = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            SortOrder = 21
                        },
                        new
                        {
                            Id = "c0a1b2c3-d4e5-4f6a-7b8c-9d0e1f2a3b4c",
                            Abbreviation = "m",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "米",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 22
                        },
                        new
                        {
                            Id = "d1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            Abbreviation = "km",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千米",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 23
                        },
                        new
                        {
                            Id = "e2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            Abbreviation = "cm",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "厘米",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 24
                        },
                        new
                        {
                            Id = "f3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            Abbreviation = "mm",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "毫米",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 25
                        },
                        new
                        {
                            Id = "a4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a",
                            Abbreviation = "mi",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "英里",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 26
                        },
                        new
                        {
                            Id = "b5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b",
                            Abbreviation = "yd",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "码",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 27
                        },
                        new
                        {
                            Id = "c6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c",
                            Abbreviation = "ft",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "英尺",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 28
                        },
                        new
                        {
                            Id = "d7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d",
                            Abbreviation = "in",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "英寸",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 29
                        },
                        new
                        {
                            Id = "e8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e",
                            Abbreviation = "kg",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千克",
                            ParentId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = "f9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f",
                            Abbreviation = "g",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "克",
                            ParentId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            SortOrder = 31
                        },
                        new
                        {
                            Id = "a0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a",
                            Abbreviation = "mg",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "毫克",
                            ParentId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            SortOrder = 32
                        },
                        new
                        {
                            Id = "b1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b",
                            Abbreviation = "t",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "吨",
                            ParentId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            SortOrder = 33
                        },
                        new
                        {
                            Id = "c2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c",
                            Abbreviation = "lb",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "磅",
                            ParentId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            SortOrder = 34
                        },
                        new
                        {
                            Id = "d3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d",
                            Abbreviation = "oz",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "盎司",
                            ParentId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            SortOrder = 35
                        },
                        new
                        {
                            Id = "e4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e",
                            Abbreviation = "s",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "秒",
                            ParentId = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            SortOrder = 36
                        },
                        new
                        {
                            Id = "f5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            Abbreviation = "min",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "分钟",
                            ParentId = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            SortOrder = 37
                        },
                        new
                        {
                            Id = "a6e7f8a9-b0c1-4d2e-3f4a-5b6c7d8e9f0a",
                            Abbreviation = "h",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "小时",
                            ParentId = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            SortOrder = 38
                        },
                        new
                        {
                            Id = "b7f8a9b0-c1d2-4e3f-4a5b-6c7d8e9f0a1b",
                            Abbreviation = "d",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "天",
                            ParentId = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            SortOrder = 39
                        },
                        new
                        {
                            Id = "c8a9b0c1-d2e3-4f4a-5b6c-7d8e9f0a1b2c",
                            Abbreviation = "°C",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "摄氏度",
                            ParentId = "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = "d9b0c1d2-e3f4-4a5b-6c7d-8e9f0a1b2c3d",
                            Abbreviation = "°F",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "华氏度",
                            ParentId = "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a",
                            SortOrder = 41
                        },
                        new
                        {
                            Id = "e0c1d2e3-f4a5-4b6c-7d8e-9f0a1b2c3d4e",
                            Abbreviation = "K",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "开尔文",
                            ParentId = "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a",
                            SortOrder = 42
                        },
                        new
                        {
                            Id = "f1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f",
                            Abbreviation = "A",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "安培",
                            ParentId = "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b",
                            SortOrder = 43
                        },
                        new
                        {
                            Id = "a2e3f4a5-b6c7-4d8e-9f0a-1b2c3d4e5f6a",
                            Abbreviation = "mA",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "毫安",
                            ParentId = "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b",
                            SortOrder = 44
                        },
                        new
                        {
                            Id = "b3f4a5b6-c7d8-4e9f-0a1b-2c3d4e5f6a7b",
                            Abbreviation = "µA",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "微安",
                            ParentId = "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b",
                            SortOrder = 45
                        },
                        new
                        {
                            Id = "c4a5b6c7-d8e9-4f0a-1b2c-3d4e5f6a7b8c",
                            Abbreviation = "V",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "伏特",
                            ParentId = "f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c",
                            SortOrder = 46
                        },
                        new
                        {
                            Id = "d5b6c7d8-e9f0-4a1b-2c3d-4e5f6a7b8c9d",
                            Abbreviation = "kV",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千伏",
                            ParentId = "f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c",
                            SortOrder = 47
                        },
                        new
                        {
                            Id = "e6c7d8e9-f0a1-4b2c-3d4e-5f6a7b8c9d0e",
                            Abbreviation = "mV",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "毫伏",
                            ParentId = "f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c",
                            SortOrder = 48
                        },
                        new
                        {
                            Id = "f7d8e9f0-a1b2-4c3d-4e5f-6a7b8c9d0e1f",
                            Abbreviation = "W",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "瓦特",
                            ParentId = "a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d",
                            SortOrder = 49
                        },
                        new
                        {
                            Id = "a8e9f0a1-b2c3-4d4e-5f6a-7b8c9d0e1f2a",
                            Abbreviation = "kW",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千瓦",
                            ParentId = "a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = "b9f0a1b2-c3d4-4e5f-6a7b-8c9d0e1f2a3b",
                            Abbreviation = "MW",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "兆瓦",
                            ParentId = "a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d",
                            SortOrder = 51
                        },
                        new
                        {
                            Id = "a00be966-be2e-484e-92b6-9706494ac775",
                            Abbreviation = "hp",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "马力",
                            ParentId = "a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d",
                            SortOrder = 52
                        },
                        new
                        {
                            Id = "e88b04db-40ac-4bb7-b420-1f3b37180673",
                            Abbreviation = "m²",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "平方米",
                            ParentId = "b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e",
                            SortOrder = 53
                        },
                        new
                        {
                            Id = "0d7ebe17-93ae-4e4c-92f4-063a124cd181",
                            Abbreviation = "km²",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "平方公里",
                            ParentId = "b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e",
                            SortOrder = 54
                        },
                        new
                        {
                            Id = "a4c312d3-023e-4d4e-b5a7-fb7fcbd55c56",
                            Abbreviation = "ha",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "公顷",
                            ParentId = "b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e",
                            SortOrder = 55
                        },
                        new
                        {
                            Id = "fefa26a5-d608-411c-b637-469a886e558c",
                            Abbreviation = "亩",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "亩",
                            ParentId = "b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e",
                            SortOrder = 56
                        },
                        new
                        {
                            Id = "2d21c35a-4251-479e-b814-060b2fc84445",
                            Abbreviation = "m³",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "立方米",
                            ParentId = "c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f",
                            SortOrder = 57
                        },
                        new
                        {
                            Id = "7f0af6a9-ba1a-469c-b967-e32afe43cad2",
                            Abbreviation = "L",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "升",
                            ParentId = "c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f",
                            SortOrder = 58
                        },
                        new
                        {
                            Id = "780e7a01-350d-45ec-b963-b36a996de614",
                            Abbreviation = "mL",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "毫升",
                            ParentId = "c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f",
                            SortOrder = 59
                        },
                        new
                        {
                            Id = "4cbec89d-3f52-4db3-9ab0-faeeb841ffbf",
                            Abbreviation = "m/s",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "米/秒",
                            ParentId = "d0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a",
                            SortOrder = 60
                        },
                        new
                        {
                            Id = "64e918fb-ee9d-45c7-b35a-2a55f5a5fe62",
                            Abbreviation = "km/h",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千米/小时",
                            ParentId = "d0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a",
                            SortOrder = 61
                        },
                        new
                        {
                            Id = "405ae7a3-8a13-479d-bc1a-6f9d3c15e521",
                            Abbreviation = "mph",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "英里/小时",
                            ParentId = "d0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a",
                            SortOrder = 62
                        },
                        new
                        {
                            Id = "221d3c45-911f-4e94-9c3e-c13e6f2bcc76",
                            Abbreviation = "Pa",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "帕斯卡",
                            ParentId = "e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b",
                            SortOrder = 63
                        },
                        new
                        {
                            Id = "883a9940-84ec-4daa-8448-609461b984ea",
                            Abbreviation = "kPa",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千帕",
                            ParentId = "e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b",
                            SortOrder = 64
                        },
                        new
                        {
                            Id = "d5306eb8-324f-4088-a867-6fbc7141fd59",
                            Abbreviation = "MPa",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "兆帕",
                            ParentId = "e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b",
                            SortOrder = 65
                        },
                        new
                        {
                            Id = "8981bd9a-bd99-4f4c-b8af-038975b799be",
                            Abbreviation = "bar",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "巴",
                            ParentId = "e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b",
                            SortOrder = 66
                        },
                        new
                        {
                            Id = "5db494d7-2a9c-4ae0-86e0-d4bb0dfc7b81",
                            Abbreviation = "J",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "焦耳",
                            ParentId = "f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c",
                            SortOrder = 67
                        },
                        new
                        {
                            Id = "279a6b18-6d01-4437-b95b-0480ca7adc98",
                            Abbreviation = "kJ",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千焦",
                            ParentId = "f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c",
                            SortOrder = 68
                        },
                        new
                        {
                            Id = "e3c1f025-3b2b-461a-a5a1-015cb4e3fe38",
                            Abbreviation = "kWh",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千瓦时",
                            ParentId = "f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c",
                            SortOrder = 69
                        },
                        new
                        {
                            Id = "5e880060-9410-40d7-bcb4-545ccd0c1bb6",
                            Abbreviation = "Hz",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "赫兹",
                            ParentId = "a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d",
                            SortOrder = 70
                        },
                        new
                        {
                            Id = "1a80ed3b-1b36-4d8b-b80b-3070dbc7979d",
                            Abbreviation = "kHz",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千赫",
                            ParentId = "a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d",
                            SortOrder = 71
                        },
                        new
                        {
                            Id = "41572712-95dd-4caf-b316-e1b924bc57c3",
                            Abbreviation = "MHz",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "兆赫",
                            ParentId = "a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d",
                            SortOrder = 72
                        },
                        new
                        {
                            Id = "ed1b66d2-454b-453b-9d43-12605dffa456",
                            Abbreviation = "°",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "度",
                            ParentId = "b4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e",
                            SortOrder = 73
                        },
                        new
                        {
                            Id = "3d9088a3-7283-4f8f-b995-b193a57a6c2a",
                            Abbreviation = "rad",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "弧度",
                            ParentId = "b4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e",
                            SortOrder = 74
                        });
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.AttributeDefinition", b =>
                {
                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.CompositeTypeDefinition", "RefCompositeType")
                        .WithMany()
                        .HasForeignKey("RefCompositeTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.OptionSet", "RefOptionSet")
                        .WithMany()
                        .HasForeignKey("RefOptionSetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.CustomTableDefinition", "RefTableDefinition")
                        .WithMany()
                        .HasForeignKey("RefTableDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RefCompositeType");

                    b.Navigation("RefOptionSet");

                    b.Navigation("RefTableDefinition");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.AttributeValue", b =>
                {
                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.AttributeDefinition", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Attribute");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CompositeFieldDefinition", b =>
                {
                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.CompositeTypeDefinition", "CompositeType")
                        .WithMany("Fields")
                        .HasForeignKey("CompositeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.CompositeTypeDefinition", "RefCompositeType")
                        .WithMany()
                        .HasForeignKey("RefCompositeTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.OptionSet", "RefOptionSet")
                        .WithMany()
                        .HasForeignKey("RefOptionSetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompositeType");

                    b.Navigation("RefCompositeType");

                    b.Navigation("RefOptionSet");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CustomTableColumn", b =>
                {
                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.CompositeTypeDefinition", "RefCompositeType")
                        .WithMany()
                        .HasForeignKey("RefCompositeTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.CustomTableDefinition", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RefCompositeType");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CustomTableRow", b =>
                {
                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.AttributeDefinition", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.CustomTableDefinition", "Table")
                        .WithMany()
                        .HasForeignKey("TableDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.OptionItem", b =>
                {
                    b.HasOne("TreeGraph.Api.NodeEavSky.Entities.OptionSet", "OptionSet")
                        .WithMany("Items")
                        .HasForeignKey("OptionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionSet");
                });

            modelBuilder.Entity("TreeGraph.Api.StringTreeSky.Entities.StringNodeEntity", b =>
                {
                    b.HasOne("TreeGraph.Api.StringTreeSky.Entities.StringNodeEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TreeGraph.Shared.TreeSky.Entities.UnitTree", b =>
                {
                    b.HasOne("TreeGraph.Shared.TreeSky.Entities.UnitTree", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CompositeTypeDefinition", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.CustomTableDefinition", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("TreeGraph.Api.NodeEavSky.Entities.OptionSet", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TreeGraph.Api.StringTreeSky.Entities.StringNodeEntity", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
