<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AI.Foundry.Local" Version="2.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" />
        <PackageReference Include="OpenAI" Version="2.14.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\APromisedLand.Api\APromisedLand.Api.csproj" />
      <ProjectReference Include="..\APromisedLand.ServiceDefaults\APromisedLand.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>
