<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.5.3" />
        <PackageReference Include="AWSSDK.S3" Version="4.0.103.1" />
        <PackageReference Include="Hangfire.Core" Version="1.8.25" />
        <PackageReference Include="Microsoft.Agents.AI" Version="1.20.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Polly" Version="8.7.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\APromisedLand.Api\APromisedLand.Api.csproj" />
      <ProjectReference Include="..\APromisedLand.ServiceDefaults\APromisedLand.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>
