<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.5.3" />
        <PackageReference Include="AWSSDK.S3" Version="4.0.103.1" />
        <PackageReference Include="CommunityToolkit.Aspire.OllamaSharp" Version="13.5.0" />
        <PackageReference Include="Hangfire.AspNetCore" Version="1.8.25" />
        <PackageReference Include="Hangfire.Core" Version="1.8.25" />
        <PackageReference Include="Hangfire.PostgreSql" Version="1.21.1" />
        <PackageReference Include="Microsoft.Agents.AI" Version="1.20.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="10.0.12" />
        <PackageReference Include="Npgsql.OpenTelemetry" Version="10.0.3" />
        <PackageReference Include="OpenTelemetry" Version="1.18.0" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.18.0" />
        <PackageReference Include="Polly" Version="8.7.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\APromisedLand.Api\APromisedLand.Api.csproj" />
      <ProjectReference Include="..\APromisedLand.ServiceDefaults\APromisedLand.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>
