@FileTransService_HostAddress = http://localhost:5033

GET {{FileTransService_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{FileTransService_HostAddress}}/FileTrans/upload?businessId=demo2026"
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="hello.txt"

< hello.txt
--WebAppBoundary--

###
GET http://localhost:5033/FileTrans/download/38f298e4-25a4-42d6-9477-021352eae622

###
DELETE http://localhost:5033/FileTrans/38f298e4-25a4-42d6-9477-021352eae622

###