// <auto-generated />
using APromisedLand.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APromisedLand.Api.Data.Migrations
{
    [DbContext(typeof(DiberyDbContext))]
    [Migration("20260726054513_UnitOfMeasure")]
    partial class UnitOfMeasure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APromisedLand.Api.Models.UnitOfMeasure", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UnitsOfMeasure", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7d9b6f2e-1a3c-48f7-9b8d-5e6a1c2d3f40",
                            Description = "公斤",
                            IsActive = true,
                            Name = "千克",
                            Symbol = "kg"
                        },
                        new
                        {
                            Id = "a3c8e0f5-6b4d-4a1e-9f2c-8d7b1e5a6f30",
                            IsActive = true,
                            Name = "克",
                            Symbol = "g"
                        },
                        new
                        {
                            Id = "b2d4f6a8-c0e2-4f1b-8a3d-1c5e7b9d2f44",
                            IsActive = true,
                            Name = "毫克",
                            Symbol = "mg"
                        },
                        new
                        {
                            Id = "c1e3a5f7-d9b1-4e8c-9d2a-5b7c0e1f3a62",
                            Description = "公吨",
                            IsActive = true,
                            Name = "吨",
                            Symbol = "t"
                        },
                        new
                        {
                            Id = "f8a2c4e6-1b3d-4f5c-8a9b-7d0e1f2a3b55",
                            Description = "公升",
                            IsActive = true,
                            Name = "升",
                            Symbol = "L"
                        },
                        new
                        {
                            Id = "e7d9b1f3-2c4a-4e6b-8d5c-0f1a2b3c4d66",
                            IsActive = true,
                            Name = "毫升",
                            Symbol = "mL"
                        },
                        new
                        {
                            Id = "d6f8a0b2-3c4e-4a6d-8b1c-9d0e1f2a3b77",
                            Description = "公尺",
                            IsActive = true,
                            Name = "米",
                            Symbol = "m"
                        },
                        new
                        {
                            Id = "c5e7b9d1-4f0a-4c2e-8a3b-7b8d9e0f1c88",
                            Description = "公分",
                            IsActive = true,
                            Name = "厘米",
                            Symbol = "cm"
                        },
                        new
                        {
                            Id = "b4d6f8a0-5e1b-4d3c-9a2b-6c7d8e9f0a99",
                            IsActive = true,
                            Name = "毫米",
                            Symbol = "mm"
                        },
                        new
                        {
                            Id = "a3c5e7f9-6b1d-4f4a-8c2b-5d6e7f8a9b00",
                            Description = "公里",
                            IsActive = true,
                            Name = "千米",
                            Symbol = "km"
                        },
                        new
                        {
                            Id = "92b4d6f8-7c0e-4a5b-9d1a-4c5d6e7f8a11",
                            Description = "件、只",
                            IsActive = true,
                            Name = "个",
                            Symbol = "pcs"
                        },
                        new
                        {
                            Id = "81a3c5e7-8d1f-4b6c-8e2a-3b4c5d6e7f22",
                            IsActive = true,
                            Name = "箱",
                            Symbol = "box"
                        },
                        new
                        {
                            Id = "70f2a4b6-9e0c-4d7a-8f3b-2a3b4c5d6e33",
                            IsActive = true,
                            Name = "包",
                            Symbol = "bag"
                        },
                        new
                        {
                            Id = "6e1f3a5b-0d8e-4c8a-9d4b-1a2b3c4d5e44",
                            IsActive = true,
                            Name = "瓶",
                            Symbol = "bottle"
                        },
                        new
                        {
                            Id = "5d0e2f4a-1c9f-4b9c-8e5a-0f1a2b3c4d55",
                            Description = "听",
                            IsActive = true,
                            Name = "罐",
                            Symbol = "can"
                        },
                        new
                        {
                            Id = "4c9f1e3b-2d0a-4c8e-9f6a-9e0f1a2b3c66",
                            IsActive = true,
                            Name = "双",
                            Symbol = "pair"
                        },
                        new
                        {
                            Id = "3b8e0d2c-3f1b-4d9f-8a7b-8d9e0f1a2b77",
                            IsActive = true,
                            Name = "套",
                            Symbol = "set"
                        },
                        new
                        {
                            Id = "2a7d9f1b-4e2c-4e0a-9b8c-7c8d9e0f1a88",
                            IsActive = true,
                            Name = "卷",
                            Symbol = "roll"
                        },
                        new
                        {
                            Id = "1c6e8a0d-5f3d-4f1b-8c9d-6b7c8d9e0f99",
                            Description = "平方公尺",
                            IsActive = true,
                            Name = "平方米",
                            Symbol = "m²"
                        },
                        new
                        {
                            Id = "0b5d7f9e-6a4e-4f2c-9d0e-5a6b7c8d9e00",
                            Description = "立方公尺",
                            IsActive = true,
                            Name = "立方米",
                            Symbol = "m³"
                        },
                        new
                        {
                            Id = "f9a1b3c5-7d0e-4a2f-8b4d-3c5e7f9a1b11",
                            Description = "电压单位",
                            IsActive = true,
                            Name = "伏特",
                            Symbol = "V"
                        },
                        new
                        {
                            Id = "e8b2c4d6-1f3a-4b5c-9d6e-2d4f6a8b0c22",
                            Description = "千伏特",
                            IsActive = true,
                            Name = "千伏",
                            Symbol = "kV"
                        },
                        new
                        {
                            Id = "d7c3d5e7-2a4b-4c6d-8e7f-1c3e5a7b9d33",
                            Description = "电流单位",
                            IsActive = true,
                            Name = "安培",
                            Symbol = "A"
                        },
                        new
                        {
                            Id = "c6d4e6f8-3b5c-4d7e-9f8a-0b2d4f6a8c44",
                            Description = "毫安培",
                            IsActive = true,
                            Name = "毫安",
                            Symbol = "mA"
                        },
                        new
                        {
                            Id = "b5e5f7a9-4c6d-4e8f-8a9b-9a1c3e5b7d55",
                            Description = "功率单位",
                            IsActive = true,
                            Name = "瓦特",
                            Symbol = "W"
                        },
                        new
                        {
                            Id = "a4f6a8b0-5d7e-4f9a-9b0c-8b2d4f6a8c66",
                            Description = "千瓦特",
                            IsActive = true,
                            Name = "千瓦",
                            Symbol = "kW"
                        },
                        new
                        {
                            Id = "93e7b9c1-6e8f-4a0b-8c1d-7c3e5a7b9d77",
                            Description = "兆瓦特",
                            IsActive = true,
                            Name = "兆瓦",
                            Symbol = "MW"
                        },
                        new
                        {
                            Id = "82d8c0d2-7f9a-4b1c-9d2e-6d4f6a8b0c88",
                            Description = "度，电能单位",
                            IsActive = true,
                            Name = "千瓦时",
                            Symbol = "kWh"
                        },
                        new
                        {
                            Id = "71c9d1e3-8a0b-4c2d-8e3f-5e5f7a9b1c99",
                            Description = "千度，电能单位",
                            IsActive = true,
                            Name = "兆瓦时",
                            Symbol = "MWh"
                        },
                        new
                        {
                            Id = "60b0e2f4-9b1c-4d3e-9f4a-4f6a8b0c2d00",
                            Description = "能量单位",
                            IsActive = true,
                            Name = "焦耳",
                            Symbol = "J"
                        },
                        new
                        {
                            Id = "5f1a3b5c-0c2d-4e4f-8a5b-3e5f7a9b1c11",
                            Description = "频率单位",
                            IsActive = true,
                            Name = "赫兹",
                            Symbol = "Hz"
                        },
                        new
                        {
                            Id = "4e2b4c6d-1d3e-4f5a-9b6c-2d4f6a8b0c22",
                            Description = "千赫兹",
                            IsActive = true,
                            Name = "千赫",
                            Symbol = "kHz"
                        },
                        new
                        {
                            Id = "3d3c5d7e-2e4f-4a6b-8c7d-1c3e5a7b9d33",
                            Description = "电阻单位",
                            IsActive = true,
                            Name = "欧姆",
                            Symbol = "Ω"
                        },
                        new
                        {
                            Id = "2c4d6e8f-3f5a-4b7c-9d8e-0b2d4f6a8c44",
                            Description = "视在功率单位",
                            IsActive = true,
                            Name = "伏安",
                            Symbol = "VA"
                        },
                        new
                        {
                            Id = "1b5e7f9a-4a6b-4c8d-8e9f-9a1c3e5b7d55",
                            Description = "无功功率单位",
                            IsActive = true,
                            Name = "乏",
                            Symbol = "var"
                        },
                        new
                        {
                            Id = "8f2e6a1d-3b4c-45f7-9e1a-2c3d4e5f6a70",
                            Description = "摄氏温标",
                            IsActive = true,
                            Name = "摄氏度",
                            Symbol = "°C"
                        },
                        new
                        {
                            Id = "9c4a7b2e-5d6e-41a8-bf3c-0d1e2f3a4b81",
                            Description = "华氏温标",
                            IsActive = true,
                            Name = "华氏度",
                            Symbol = "°F"
                        },
                        new
                        {
                            Id = "0e1d6c3b-7f8a-42c9-9d4e-1f2a3b4c5d92",
                            Description = "热力学温标",
                            IsActive = true,
                            Name = "开尔文",
                            Symbol = "K"
                        });
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Models.CategoryTree", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CategoryTrees");

                    b.HasData(
                        new
                        {
                            Id = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            Description = "根分类示例",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample Root",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "39EA6315-0A74-40F6-A096-8E15CCC98579",
                            Description = "子分类 1",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 1",
                            ParentId = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "C1EBEE10-97F6-44C8-9852-2F574515BF51",
                            Description = "子分类 1.1",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 1.1",
                            ParentId = "39EA6315-0A74-40F6-A096-8E15CCC98579",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "C8969ED0-C018-4FDC-AE55-C363BD95C853",
                            Description = "子分类 2",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 2",
                            ParentId = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "ED0990CF-5BB7-4C36-A3BB-3AF606AD1974",
                            Description = "子分类 2.1",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 2.1",
                            ParentId = "C8969ED0-C018-4FDC-AE55-C363BD95C853",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "975599CC-B967-4AD2-B4B8-9E00D889FB4D",
                            Description = "子分类 2.2 [Archived]",
                            IsActive = false,
                            IsArchived = true,
                            Name = "Sample 2.2",
                            ParentId = "C8969ED0-C018-4FDC-AE55-C363BD95C853",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            Description = "子分类 3",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 3",
                            ParentId = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "8E971C0E-B99A-4931-AFD6-46E44D6ECE5A",
                            Description = "子分类 3.1",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 3.1",
                            ParentId = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "5C30BACA-3C11-4677-8123-8EC2BE729667",
                            Description = "子分类 3.2",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 3.2",
                            ParentId = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "1B16336D-FB7F-42AA-AFD2-F78388883336",
                            Description = "子分类 3.3",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 3.3",
                            ParentId = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "35F02829-6490-467E-9D3E-C2EBF0EAA2B4",
                            Description = "子分类 3.3.1",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 3.3.1",
                            ParentId = "1B16336D-FB7F-42AA-AFD2-F78388883336",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Models.CategoryTree", b =>
                {
                    b.HasOne("APromisedLand.Shared.DiberyTree.Models.CategoryTree", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Models.CategoryTree", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
