// <auto-generated />
using System;
using APromisedLand.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APromisedLand.Api.Data.Migrations
{
    [DbContext(typeof(DiberyDbContext))]
    partial class DiberyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Attributes.Models.AttributeDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("AttributeTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int?>("Lines")
                        .HasColumnType("integer");

                    b.Property<int>("MaxLength")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("ParentId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int?>("Precision")
                        .HasColumnType("integer");

                    b.Property<int?>("Scale")
                        .HasColumnType("integer");

                    b.Property<string>("UnitId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("UnitId");

                    b.ToTable("AttributeDefinitions");

                    b.HasData(
                        new
                        {
                            Id = "b1c2d3e4-f5a6-4b7c-8d9e-0f1a2b3c4d5e",
                            AttributeTypeId = "3f8f6d3a-9c2b-4d8f-9a6e-5b7c8d9e0f1a",
                            IsRequired = false,
                            Lines = 1,
                            MaxLength = 50,
                            Name = "名称",
                            Order = 0
                        },
                        new
                        {
                            Id = "c2d3e4f5-a6b7-4c8d-9e0f-1a2b3c4d5e6f",
                            AttributeTypeId = "3f8f6d3a-9c2b-4d8f-9a6e-5b7c8d9e0f1a",
                            IsRequired = false,
                            Lines = 5,
                            MaxLength = 500,
                            Name = "描述",
                            Order = 0
                        },
                        new
                        {
                            Id = "d3e4f5a6-b7c8-4d9e-0f1a-2b3c4d5e6f7a",
                            AttributeTypeId = "3f8f6d3a-9c2b-4d8f-9a6e-5b7c8d9e0f1a",
                            IsRequired = false,
                            Lines = 10,
                            MaxLength = 1000,
                            Name = "备注",
                            Order = 0
                        },
                        new
                        {
                            Id = "e4f5a6b7-c8d9-4e0f-1a2b-3c4d5e6f7a8b",
                            AttributeTypeId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "数量",
                            Order = 0,
                            UnitId = "c0a1b2c3-d4e5-4f6a-7b8c-9d0e1f2a3b4c"
                        },
                        new
                        {
                            Id = "f5a6b7c8-d9e0-4f1a-2b3c-4d5e6f7a8b9c",
                            AttributeTypeId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "等级",
                            Order = 0
                        },
                        new
                        {
                            Id = "a6b7c8d9-e0f1-4a2b-3c4d-5e6f7a8b9c0d",
                            AttributeTypeId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "价格",
                            Order = 0,
                            Precision = 18,
                            Scale = 2
                        },
                        new
                        {
                            Id = "b7c8d9e0-f1a2-4b3c-4d5e-6f7a8b9c0d1e",
                            AttributeTypeId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "重量",
                            Order = 0,
                            Precision = 10,
                            Scale = 3,
                            UnitId = "e8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e"
                        },
                        new
                        {
                            Id = "c8d9e0f1-a2b3-4c4d-5e6f-7a8b9c0d1e2f",
                            AttributeTypeId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "长度",
                            Order = 0,
                            Precision = 8,
                            Scale = 2,
                            UnitId = "e2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"
                        },
                        new
                        {
                            Id = "d9e0f1a2-b3c4-4d5e-6f7a-8b9c0d1e2f3a",
                            AttributeTypeId = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "生产日期",
                            Order = 0
                        },
                        new
                        {
                            Id = "e0f1a2b3-c4d5-4e6f-7a8b-9c0d1e2f3a4b",
                            AttributeTypeId = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "试验日期",
                            Order = 0
                        },
                        new
                        {
                            Id = "f1a2b3c4-d5e6-4f7a-8b9c-0d1e2f3a4b5c",
                            AttributeTypeId = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "出厂日期",
                            Order = 0
                        },
                        new
                        {
                            Id = "a2b3c4d5-e6f7-4a8b-9c0d-1e2f3a4b5c6d",
                            AttributeTypeId = "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "开始时间",
                            Order = 0
                        },
                        new
                        {
                            Id = "b3c4d5e6-f7a8-4b9c-0d1e-2f3a4b5c6d7e",
                            AttributeTypeId = "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "结束时间",
                            Order = 0
                        },
                        new
                        {
                            Id = "c4d5e6f7-a8b9-4c0d-1e2f-3a4b5c6d7e8f",
                            AttributeTypeId = "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "创建时间",
                            Order = 0
                        },
                        new
                        {
                            Id = "d5e6f7a8-b9c0-4d1e-2f3a-4b5c6d7e8f9a",
                            AttributeTypeId = "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "更新时间",
                            Order = 0
                        },
                        new
                        {
                            Id = "e6f7a8b9-c0d1-4e2f-3a4b-5c6d7e8f9a0b",
                            AttributeTypeId = "f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "附件",
                            Order = 0
                        },
                        new
                        {
                            Id = "f7a8b9c0-d1e2-4f3a-4b5c-6d7e8f9a0b1c",
                            AttributeTypeId = "f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "图片",
                            Order = 0
                        },
                        new
                        {
                            Id = "a8b9c0d1-e2f3-4a4b-5c6d-7e8f9a0b1c2d",
                            AttributeTypeId = "a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "位置坐标",
                            Order = 0
                        },
                        new
                        {
                            Id = "1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5e",
                            AttributeTypeId = "b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "规格表",
                            Order = 0
                        },
                        new
                        {
                            Id = "2b3c4d5e-6f7a-4b8c-9d0e-1f2a3b4c5d6f",
                            AttributeTypeId = "3f8f6d3a-9c2b-4d8f-9a6e-5b7c8d9e0f1a",
                            IsRequired = true,
                            Lines = 1,
                            MaxLength = 50,
                            Name = "规格-材质",
                            Order = 1,
                            ParentId = "1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5e"
                        },
                        new
                        {
                            Id = "3c4d5e6f-7a8b-4c9d-0e1f-2a3b4c5d6e7a",
                            AttributeTypeId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            IsRequired = false,
                            MaxLength = 30,
                            Name = "规格-长度",
                            Order = 2,
                            ParentId = "1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5e",
                            Precision = 8,
                            Scale = 2,
                            UnitId = "e2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"
                        });
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Attributes.Models.AttributeValueBase", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("AttributeDefinitionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Models.CategoryTree", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("CanHaveChildren")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CategoryTrees");

                    b.HasData(
                        new
                        {
                            Id = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            CanHaveChildren = false,
                            Description = "根分类示例",
                            IsArchived = false,
                            Name = "Sample Root",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "39EA6315-0A74-40F6-A096-8E15CCC98579",
                            CanHaveChildren = false,
                            Description = "子分类 1",
                            IsArchived = false,
                            Name = "Sample 1",
                            ParentId = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "C1EBEE10-97F6-44C8-9852-2F574515BF51",
                            CanHaveChildren = false,
                            Description = "子分类 1.1",
                            IsArchived = false,
                            Name = "Sample 1.1",
                            ParentId = "39EA6315-0A74-40F6-A096-8E15CCC98579",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "C8969ED0-C018-4FDC-AE55-C363BD95C853",
                            CanHaveChildren = false,
                            Description = "子分类 2",
                            IsArchived = false,
                            Name = "Sample 2",
                            ParentId = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "ED0990CF-5BB7-4C36-A3BB-3AF606AD1974",
                            CanHaveChildren = false,
                            Description = "子分类 2.1",
                            IsArchived = false,
                            Name = "Sample 2.1",
                            ParentId = "C8969ED0-C018-4FDC-AE55-C363BD95C853",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "975599CC-B967-4AD2-B4B8-9E00D889FB4D",
                            CanHaveChildren = false,
                            Description = "子分类 2.2 [Archived]",
                            IsArchived = true,
                            Name = "Sample 2.2",
                            ParentId = "C8969ED0-C018-4FDC-AE55-C363BD95C853",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            CanHaveChildren = false,
                            Description = "子分类 3",
                            IsArchived = false,
                            Name = "Sample 3",
                            ParentId = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "8E971C0E-B99A-4931-AFD6-46E44D6ECE5A",
                            CanHaveChildren = false,
                            Description = "子分类 3.1",
                            IsArchived = false,
                            Name = "Sample 3.1",
                            ParentId = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "5C30BACA-3C11-4677-8123-8EC2BE729667",
                            CanHaveChildren = false,
                            Description = "子分类 3.2",
                            IsArchived = false,
                            Name = "Sample 3.2",
                            ParentId = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "1B16336D-FB7F-42AA-AFD2-F78388883336",
                            CanHaveChildren = false,
                            Description = "子分类 3.3",
                            IsArchived = false,
                            Name = "Sample 3.3",
                            ParentId = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "35F02829-6490-467E-9D3E-C2EBF0EAA2B4",
                            CanHaveChildren = false,
                            Description = "子分类 3.3.1",
                            IsArchived = false,
                            Name = "Sample 3.3.1",
                            ParentId = "1B16336D-FB7F-42AA-AFD2-F78388883336",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Models.UnitTree", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CanHaveChildren")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentId")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("UnitTrees");

                    b.HasData(
                        new
                        {
                            Id = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "",
                            HasChildren = true,
                            Name = "计量单位",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "货币计量单位",
                            HasChildren = true,
                            Name = "货币",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "长度计量单位",
                            HasChildren = true,
                            Name = "长度",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "质量计量单位",
                            HasChildren = true,
                            Name = "质量",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "时间计量单位",
                            HasChildren = true,
                            Name = "时间",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "温度计量单位",
                            HasChildren = true,
                            Name = "温度",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "电流计量单位",
                            HasChildren = true,
                            Name = "电流",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = "f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "电压计量单位",
                            HasChildren = true,
                            Name = "电压",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = "a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "功率计量单位",
                            HasChildren = true,
                            Name = "功率",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = "b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "面积计量单位",
                            HasChildren = true,
                            Name = "面积",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = "c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "体积计量单位",
                            HasChildren = true,
                            Name = "体积",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = "d0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "速度计量单位",
                            HasChildren = true,
                            Name = "速度",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = "e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "压力计量单位",
                            HasChildren = true,
                            Name = "压力",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = "f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "能量计量单位",
                            HasChildren = true,
                            Name = "能量",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = "a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "频率计量单位",
                            HasChildren = true,
                            Name = "频率",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = "b4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e",
                            Abbreviation = "",
                            CanHaveChildren = true,
                            Description = "角度计量单位",
                            HasChildren = true,
                            Name = "角度",
                            ParentId = "9AB5700C-68F2-43F3-9D7E-805E7D5C539B",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = "f7a8b9c0-d1e2-4f3a-4b5c-6d7e8f9a0b1c",
                            Abbreviation = "CNY",
                            CanHaveChildren = false,
                            Description = "人民币",
                            HasChildren = false,
                            Name = "元",
                            ParentId = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = "e6b7c8d9-f0a1-4b2c-3d4e-5f6a7b8c9d0e",
                            Abbreviation = "USD",
                            CanHaveChildren = false,
                            Description = "美元",
                            HasChildren = false,
                            Name = "美元",
                            ParentId = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = "d5c6d7e8-f9a0-4b1c-2d3e-4f5a6b7c8d9e",
                            Abbreviation = "EUR",
                            CanHaveChildren = false,
                            Description = "欧元",
                            HasChildren = false,
                            Name = "欧元",
                            ParentId = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = "c4d5e6f7-a8b9-4c0d-1e2f-3a4b5c6d7e8f",
                            Abbreviation = "GBP",
                            CanHaveChildren = false,
                            Description = "英镑",
                            HasChildren = false,
                            Name = "英镑",
                            ParentId = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            SortOrder = 18
                        },
                        new
                        {
                            Id = "b3c4d5e6-f7a8-4b9c-0d1e-2f3a4b5c6d7e",
                            Abbreviation = "JPY",
                            CanHaveChildren = false,
                            Description = "日元",
                            HasChildren = false,
                            Name = "日元",
                            ParentId = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            SortOrder = 19
                        },
                        new
                        {
                            Id = "a5b6c7d8-e9f0-4a1b-2c3d-4e5f6a7b8c9d",
                            Abbreviation = "HKD",
                            CanHaveChildren = false,
                            Description = "港元",
                            HasChildren = false,
                            Name = "港元",
                            ParentId = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = "b6c7d8e9-f0a1-4b2c-3d4e-5f6a7b8c9d0e",
                            Abbreviation = "AUD",
                            CanHaveChildren = false,
                            Description = "澳元",
                            HasChildren = false,
                            Name = "澳元",
                            ParentId = "c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            SortOrder = 21
                        },
                        new
                        {
                            Id = "c0a1b2c3-d4e5-4f6a-7b8c-9d0e1f2a3b4c",
                            Abbreviation = "m",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "米",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 22
                        },
                        new
                        {
                            Id = "d1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            Abbreviation = "km",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千米",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 23
                        },
                        new
                        {
                            Id = "e2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            Abbreviation = "cm",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "厘米",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 24
                        },
                        new
                        {
                            Id = "f3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            Abbreviation = "mm",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "毫米",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 25
                        },
                        new
                        {
                            Id = "a4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a",
                            Abbreviation = "mi",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "英里",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 26
                        },
                        new
                        {
                            Id = "b5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b",
                            Abbreviation = "yd",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "码",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 27
                        },
                        new
                        {
                            Id = "c6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c",
                            Abbreviation = "ft",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "英尺",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 28
                        },
                        new
                        {
                            Id = "d7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d",
                            Abbreviation = "in",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "英寸",
                            ParentId = "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
                            SortOrder = 29
                        },
                        new
                        {
                            Id = "e8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e",
                            Abbreviation = "kg",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千克",
                            ParentId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = "f9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f",
                            Abbreviation = "g",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "克",
                            ParentId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            SortOrder = 31
                        },
                        new
                        {
                            Id = "a0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a",
                            Abbreviation = "mg",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "毫克",
                            ParentId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            SortOrder = 32
                        },
                        new
                        {
                            Id = "b1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b",
                            Abbreviation = "t",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "吨",
                            ParentId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            SortOrder = 33
                        },
                        new
                        {
                            Id = "c2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c",
                            Abbreviation = "lb",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "磅",
                            ParentId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            SortOrder = 34
                        },
                        new
                        {
                            Id = "d3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d",
                            Abbreviation = "oz",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "盎司",
                            ParentId = "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e",
                            SortOrder = 35
                        },
                        new
                        {
                            Id = "e4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e",
                            Abbreviation = "s",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "秒",
                            ParentId = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            SortOrder = 36
                        },
                        new
                        {
                            Id = "f5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f",
                            Abbreviation = "min",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "分钟",
                            ParentId = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            SortOrder = 37
                        },
                        new
                        {
                            Id = "a6e7f8a9-b0c1-4d2e-3f4a-5b6c7d8e9f0a",
                            Abbreviation = "h",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "小时",
                            ParentId = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            SortOrder = 38
                        },
                        new
                        {
                            Id = "b7f8a9b0-c1d2-4e3f-4a5b-6c7d8e9f0a1b",
                            Abbreviation = "d",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "天",
                            ParentId = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f",
                            SortOrder = 39
                        },
                        new
                        {
                            Id = "c8a9b0c1-d2e3-4f4a-5b6c-7d8e9f0a1b2c",
                            Abbreviation = "°C",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "摄氏度",
                            ParentId = "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = "d9b0c1d2-e3f4-4a5b-6c7d-8e9f0a1b2c3d",
                            Abbreviation = "°F",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "华氏度",
                            ParentId = "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a",
                            SortOrder = 41
                        },
                        new
                        {
                            Id = "e0c1d2e3-f4a5-4b6c-7d8e-9f0a1b2c3d4e",
                            Abbreviation = "K",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "开尔文",
                            ParentId = "d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a",
                            SortOrder = 42
                        },
                        new
                        {
                            Id = "f1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f",
                            Abbreviation = "A",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "安培",
                            ParentId = "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b",
                            SortOrder = 43
                        },
                        new
                        {
                            Id = "a2e3f4a5-b6c7-4d8e-9f0a-1b2c3d4e5f6a",
                            Abbreviation = "mA",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "毫安",
                            ParentId = "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b",
                            SortOrder = 44
                        },
                        new
                        {
                            Id = "b3f4a5b6-c7d8-4e9f-0a1b-2c3d4e5f6a7b",
                            Abbreviation = "µA",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "微安",
                            ParentId = "e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b",
                            SortOrder = 45
                        },
                        new
                        {
                            Id = "c4a5b6c7-d8e9-4f0a-1b2c-3d4e5f6a7b8c",
                            Abbreviation = "V",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "伏特",
                            ParentId = "f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c",
                            SortOrder = 46
                        },
                        new
                        {
                            Id = "d5b6c7d8-e9f0-4a1b-2c3d-4e5f6a7b8c9d",
                            Abbreviation = "kV",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千伏",
                            ParentId = "f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c",
                            SortOrder = 47
                        },
                        new
                        {
                            Id = "e6c7d8e9-f0a1-4b2c-3d4e-5f6a7b8c9d0e",
                            Abbreviation = "mV",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "毫伏",
                            ParentId = "f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c",
                            SortOrder = 48
                        },
                        new
                        {
                            Id = "f7d8e9f0-a1b2-4c3d-4e5f-6a7b8c9d0e1f",
                            Abbreviation = "W",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "瓦特",
                            ParentId = "a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d",
                            SortOrder = 49
                        },
                        new
                        {
                            Id = "a8e9f0a1-b2c3-4d4e-5f6a-7b8c9d0e1f2a",
                            Abbreviation = "kW",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千瓦",
                            ParentId = "a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = "b9f0a1b2-c3d4-4e5f-6a7b-8c9d0e1f2a3b",
                            Abbreviation = "MW",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "兆瓦",
                            ParentId = "a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d",
                            SortOrder = 51
                        },
                        new
                        {
                            Id = "a00be966-be2e-484e-92b6-9706494ac775",
                            Abbreviation = "hp",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "马力",
                            ParentId = "a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d",
                            SortOrder = 52
                        },
                        new
                        {
                            Id = "e88b04db-40ac-4bb7-b420-1f3b37180673",
                            Abbreviation = "m²",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "平方米",
                            ParentId = "b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e",
                            SortOrder = 53
                        },
                        new
                        {
                            Id = "0d7ebe17-93ae-4e4c-92f4-063a124cd181",
                            Abbreviation = "km²",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "平方公里",
                            ParentId = "b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e",
                            SortOrder = 54
                        },
                        new
                        {
                            Id = "a4c312d3-023e-4d4e-b5a7-fb7fcbd55c56",
                            Abbreviation = "ha",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "公顷",
                            ParentId = "b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e",
                            SortOrder = 55
                        },
                        new
                        {
                            Id = "fefa26a5-d608-411c-b637-469a886e558c",
                            Abbreviation = "亩",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "亩",
                            ParentId = "b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e",
                            SortOrder = 56
                        },
                        new
                        {
                            Id = "2d21c35a-4251-479e-b814-060b2fc84445",
                            Abbreviation = "m³",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "立方米",
                            ParentId = "c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f",
                            SortOrder = 57
                        },
                        new
                        {
                            Id = "7f0af6a9-ba1a-469c-b967-e32afe43cad2",
                            Abbreviation = "L",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "升",
                            ParentId = "c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f",
                            SortOrder = 58
                        },
                        new
                        {
                            Id = "780e7a01-350d-45ec-b963-b36a996de614",
                            Abbreviation = "mL",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "毫升",
                            ParentId = "c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f",
                            SortOrder = 59
                        },
                        new
                        {
                            Id = "4cbec89d-3f52-4db3-9ab0-faeeb841ffbf",
                            Abbreviation = "m/s",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "米/秒",
                            ParentId = "d0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a",
                            SortOrder = 60
                        },
                        new
                        {
                            Id = "64e918fb-ee9d-45c7-b35a-2a55f5a5fe62",
                            Abbreviation = "km/h",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千米/小时",
                            ParentId = "d0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a",
                            SortOrder = 61
                        },
                        new
                        {
                            Id = "405ae7a3-8a13-479d-bc1a-6f9d3c15e521",
                            Abbreviation = "mph",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "英里/小时",
                            ParentId = "d0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a",
                            SortOrder = 62
                        },
                        new
                        {
                            Id = "221d3c45-911f-4e94-9c3e-c13e6f2bcc76",
                            Abbreviation = "Pa",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "帕斯卡",
                            ParentId = "e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b",
                            SortOrder = 63
                        },
                        new
                        {
                            Id = "883a9940-84ec-4daa-8448-609461b984ea",
                            Abbreviation = "kPa",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千帕",
                            ParentId = "e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b",
                            SortOrder = 64
                        },
                        new
                        {
                            Id = "d5306eb8-324f-4088-a867-6fbc7141fd59",
                            Abbreviation = "MPa",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "兆帕",
                            ParentId = "e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b",
                            SortOrder = 65
                        },
                        new
                        {
                            Id = "8981bd9a-bd99-4f4c-b8af-038975b799be",
                            Abbreviation = "bar",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "巴",
                            ParentId = "e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b",
                            SortOrder = 66
                        },
                        new
                        {
                            Id = "5db494d7-2a9c-4ae0-86e0-d4bb0dfc7b81",
                            Abbreviation = "J",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "焦耳",
                            ParentId = "f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c",
                            SortOrder = 67
                        },
                        new
                        {
                            Id = "279a6b18-6d01-4437-b95b-0480ca7adc98",
                            Abbreviation = "kJ",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千焦",
                            ParentId = "f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c",
                            SortOrder = 68
                        },
                        new
                        {
                            Id = "e3c1f025-3b2b-461a-a5a1-015cb4e3fe38",
                            Abbreviation = "kWh",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千瓦时",
                            ParentId = "f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c",
                            SortOrder = 69
                        },
                        new
                        {
                            Id = "5e880060-9410-40d7-bcb4-545ccd0c1bb6",
                            Abbreviation = "Hz",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "赫兹",
                            ParentId = "a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d",
                            SortOrder = 70
                        },
                        new
                        {
                            Id = "1a80ed3b-1b36-4d8b-b80b-3070dbc7979d",
                            Abbreviation = "kHz",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "千赫",
                            ParentId = "a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d",
                            SortOrder = 71
                        },
                        new
                        {
                            Id = "41572712-95dd-4caf-b316-e1b924bc57c3",
                            Abbreviation = "MHz",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "兆赫",
                            ParentId = "a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d",
                            SortOrder = 72
                        },
                        new
                        {
                            Id = "ed1b66d2-454b-453b-9d43-12605dffa456",
                            Abbreviation = "°",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "度",
                            ParentId = "b4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e",
                            SortOrder = 73
                        },
                        new
                        {
                            Id = "3d9088a3-7283-4f8f-b995-b193a57a6c2a",
                            Abbreviation = "rad",
                            CanHaveChildren = false,
                            Description = "",
                            HasChildren = false,
                            Name = "弧度",
                            ParentId = "b4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e",
                            SortOrder = 74
                        });
                });

            modelBuilder.Entity("APromisedLand.Shared.Models.UnitOfMeasure", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UnitsOfMeasure", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7d9b6f2e-1a3c-48f7-9b8d-5e6a1c2d3f40",
                            Description = "公斤",
                            IsActive = true,
                            Name = "千克",
                            Symbol = "kg"
                        },
                        new
                        {
                            Id = "a3c8e0f5-6b4d-4a1e-9f2c-8d7b1e5a6f30",
                            IsActive = true,
                            Name = "克",
                            Symbol = "g"
                        },
                        new
                        {
                            Id = "b2d4f6a8-c0e2-4f1b-8a3d-1c5e7b9d2f44",
                            IsActive = true,
                            Name = "毫克",
                            Symbol = "mg"
                        },
                        new
                        {
                            Id = "c1e3a5f7-d9b1-4e8c-9d2a-5b7c0e1f3a62",
                            Description = "公吨",
                            IsActive = true,
                            Name = "吨",
                            Symbol = "t"
                        },
                        new
                        {
                            Id = "f8a2c4e6-1b3d-4f5c-8a9b-7d0e1f2a3b55",
                            Description = "公升",
                            IsActive = true,
                            Name = "升",
                            Symbol = "L"
                        },
                        new
                        {
                            Id = "e7d9b1f3-2c4a-4e6b-8d5c-0f1a2b3c4d66",
                            IsActive = true,
                            Name = "毫升",
                            Symbol = "mL"
                        },
                        new
                        {
                            Id = "d6f8a0b2-3c4e-4a6d-8b1c-9d0e1f2a3b77",
                            Description = "公尺",
                            IsActive = true,
                            Name = "米",
                            Symbol = "m"
                        },
                        new
                        {
                            Id = "c5e7b9d1-4f0a-4c2e-8a3b-7b8d9e0f1c88",
                            Description = "公分",
                            IsActive = true,
                            Name = "厘米",
                            Symbol = "cm"
                        },
                        new
                        {
                            Id = "b4d6f8a0-5e1b-4d3c-9a2b-6c7d8e9f0a99",
                            IsActive = true,
                            Name = "毫米",
                            Symbol = "mm"
                        },
                        new
                        {
                            Id = "a3c5e7f9-6b1d-4f4a-8c2b-5d6e7f8a9b00",
                            Description = "公里",
                            IsActive = true,
                            Name = "千米",
                            Symbol = "km"
                        },
                        new
                        {
                            Id = "92b4d6f8-7c0e-4a5b-9d1a-4c5d6e7f8a11",
                            Description = "件、只",
                            IsActive = true,
                            Name = "个",
                            Symbol = "pcs"
                        },
                        new
                        {
                            Id = "81a3c5e7-8d1f-4b6c-8e2a-3b4c5d6e7f22",
                            IsActive = true,
                            Name = "箱",
                            Symbol = "box"
                        },
                        new
                        {
                            Id = "70f2a4b6-9e0c-4d7a-8f3b-2a3b4c5d6e33",
                            IsActive = true,
                            Name = "包",
                            Symbol = "bag"
                        },
                        new
                        {
                            Id = "6e1f3a5b-0d8e-4c8a-9d4b-1a2b3c4d5e44",
                            IsActive = true,
                            Name = "瓶",
                            Symbol = "bottle"
                        },
                        new
                        {
                            Id = "5d0e2f4a-1c9f-4b9c-8e5a-0f1a2b3c4d55",
                            Description = "听",
                            IsActive = true,
                            Name = "罐",
                            Symbol = "can"
                        },
                        new
                        {
                            Id = "4c9f1e3b-2d0a-4c8e-9f6a-9e0f1a2b3c66",
                            IsActive = true,
                            Name = "双",
                            Symbol = "pair"
                        },
                        new
                        {
                            Id = "3b8e0d2c-3f1b-4d9f-8a7b-8d9e0f1a2b77",
                            IsActive = true,
                            Name = "套",
                            Symbol = "set"
                        },
                        new
                        {
                            Id = "2a7d9f1b-4e2c-4e0a-9b8c-7c8d9e0f1a88",
                            IsActive = true,
                            Name = "卷",
                            Symbol = "roll"
                        },
                        new
                        {
                            Id = "1c6e8a0d-5f3d-4f1b-8c9d-6b7c8d9e0f99",
                            Description = "平方公尺",
                            IsActive = true,
                            Name = "平方米",
                            Symbol = "m²"
                        },
                        new
                        {
                            Id = "0b5d7f9e-6a4e-4f2c-9d0e-5a6b7c8d9e00",
                            Description = "立方公尺",
                            IsActive = true,
                            Name = "立方米",
                            Symbol = "m³"
                        },
                        new
                        {
                            Id = "f9a1b3c5-7d0e-4a2f-8b4d-3c5e7f9a1b11",
                            Description = "电压单位",
                            IsActive = true,
                            Name = "伏特",
                            Symbol = "V"
                        },
                        new
                        {
                            Id = "e8b2c4d6-1f3a-4b5c-9d6e-2d4f6a8b0c22",
                            Description = "千伏特",
                            IsActive = true,
                            Name = "千伏",
                            Symbol = "kV"
                        },
                        new
                        {
                            Id = "d7c3d5e7-2a4b-4c6d-8e7f-1c3e5a7b9d33",
                            Description = "电流单位",
                            IsActive = true,
                            Name = "安培",
                            Symbol = "A"
                        },
                        new
                        {
                            Id = "c6d4e6f8-3b5c-4d7e-9f8a-0b2d4f6a8c44",
                            Description = "毫安培",
                            IsActive = true,
                            Name = "毫安",
                            Symbol = "mA"
                        },
                        new
                        {
                            Id = "b5e5f7a9-4c6d-4e8f-8a9b-9a1c3e5b7d55",
                            Description = "功率单位",
                            IsActive = true,
                            Name = "瓦特",
                            Symbol = "W"
                        },
                        new
                        {
                            Id = "a4f6a8b0-5d7e-4f9a-9b0c-8b2d4f6a8c66",
                            Description = "千瓦特",
                            IsActive = true,
                            Name = "千瓦",
                            Symbol = "kW"
                        },
                        new
                        {
                            Id = "93e7b9c1-6e8f-4a0b-8c1d-7c3e5a7b9d77",
                            Description = "兆瓦特",
                            IsActive = true,
                            Name = "兆瓦",
                            Symbol = "MW"
                        },
                        new
                        {
                            Id = "82d8c0d2-7f9a-4b1c-9d2e-6d4f6a8b0c88",
                            Description = "度，电能单位",
                            IsActive = true,
                            Name = "千瓦时",
                            Symbol = "kWh"
                        },
                        new
                        {
                            Id = "71c9d1e3-8a0b-4c2d-8e3f-5e5f7a9b1c99",
                            Description = "千度，电能单位",
                            IsActive = true,
                            Name = "兆瓦时",
                            Symbol = "MWh"
                        },
                        new
                        {
                            Id = "60b0e2f4-9b1c-4d3e-9f4a-4f6a8b0c2d00",
                            Description = "能量单位",
                            IsActive = true,
                            Name = "焦耳",
                            Symbol = "J"
                        },
                        new
                        {
                            Id = "5f1a3b5c-0c2d-4e4f-8a5b-3e5f7a9b1c11",
                            Description = "频率单位",
                            IsActive = true,
                            Name = "赫兹",
                            Symbol = "Hz"
                        },
                        new
                        {
                            Id = "4e2b4c6d-1d3e-4f5a-9b6c-2d4f6a8b0c22",
                            Description = "千赫兹",
                            IsActive = true,
                            Name = "千赫",
                            Symbol = "kHz"
                        },
                        new
                        {
                            Id = "3d3c5d7e-2e4f-4a6b-8c7d-1c3e5a7b9d33",
                            Description = "电阻单位",
                            IsActive = true,
                            Name = "欧姆",
                            Symbol = "Ω"
                        },
                        new
                        {
                            Id = "2c4d6e8f-3f5a-4b7c-9d8e-0b2d4f6a8c44",
                            Description = "视在功率单位",
                            IsActive = true,
                            Name = "伏安",
                            Symbol = "VA"
                        },
                        new
                        {
                            Id = "1b5e7f9a-4a6b-4c8d-8e9f-9a1c3e5b7d55",
                            Description = "无功功率单位",
                            IsActive = true,
                            Name = "乏",
                            Symbol = "var"
                        },
                        new
                        {
                            Id = "8f2e6a1d-3b4c-45f7-9e1a-2c3d4e5f6a70",
                            Description = "摄氏温标",
                            IsActive = true,
                            Name = "摄氏度",
                            Symbol = "°C"
                        },
                        new
                        {
                            Id = "9c4a7b2e-5d6e-41a8-bf3c-0d1e2f3a4b81",
                            Description = "华氏温标",
                            IsActive = true,
                            Name = "华氏度",
                            Symbol = "°F"
                        },
                        new
                        {
                            Id = "0e1d6c3b-7f8a-42c9-9d4e-1f2a3b4c5d92",
                            Description = "热力学温标",
                            IsActive = true,
                            Name = "开尔文",
                            Symbol = "K"
                        });
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Attributes.Models.DateAttributeValue", b =>
                {
                    b.HasBaseType("APromisedLand.Shared.DiberyTree.Attributes.Models.AttributeValueBase");

                    b.Property<DateTimeOffset>("Value")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("DateAttributeValues", (string)null);
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Attributes.Models.DateTimeAttributeValue", b =>
                {
                    b.HasBaseType("APromisedLand.Shared.DiberyTree.Attributes.Models.AttributeValueBase");

                    b.Property<DateTimeOffset>("Value")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("DateTimeAttributeValues", (string)null);
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Attributes.Models.DecimalAttributeValue", b =>
                {
                    b.HasBaseType("APromisedLand.Shared.DiberyTree.Attributes.Models.AttributeValueBase");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.ToTable("DecimalAttributeValues", (string)null);
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Attributes.Models.FileAttributeValue", b =>
                {
                    b.HasBaseType("APromisedLand.Shared.DiberyTree.Attributes.Models.AttributeValueBase");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FileName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.ToTable("FileAttributeValues", (string)null);
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Attributes.Models.IntegerAttributeValue", b =>
                {
                    b.HasBaseType("APromisedLand.Shared.DiberyTree.Attributes.Models.AttributeValueBase");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.ToTable("IntegerAttributeValues", (string)null);
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Attributes.Models.LocationAttributeValue", b =>
                {
                    b.HasBaseType("APromisedLand.Shared.DiberyTree.Attributes.Models.AttributeValueBase");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.ToTable("LocationAttributeValues", (string)null);
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Attributes.Models.TableAttributeValue", b =>
                {
                    b.HasBaseType("APromisedLand.Shared.DiberyTree.Attributes.Models.AttributeValueBase");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("TableAttributeValues", (string)null);
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Attributes.Models.TableRowAttributeValue", b =>
                {
                    b.HasBaseType("APromisedLand.Shared.DiberyTree.Attributes.Models.AttributeValueBase");

                    b.Property<int?>("RowNo")
                        .HasColumnType("integer");

                    b.Property<string>("TableId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.ToTable("TableRowAttributeValues", (string)null);
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Attributes.Models.TextAttributeValue", b =>
                {
                    b.HasBaseType("APromisedLand.Shared.DiberyTree.Attributes.Models.AttributeValueBase");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("TextAttributeValues", (string)null);
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Attributes.Models.TimeAttributeValue", b =>
                {
                    b.HasBaseType("APromisedLand.Shared.DiberyTree.Attributes.Models.AttributeValueBase");

                    b.Property<TimeSpan>("Value")
                        .HasColumnType("interval");

                    b.ToTable("TimeAttributeValues", (string)null);
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Attributes.Models.AttributeDefinition", b =>
                {
                    b.HasOne("APromisedLand.Shared.DiberyTree.Attributes.Models.AttributeDefinition", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("APromisedLand.Shared.DiberyTree.Models.UnitTree", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Parent");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Models.UnitTree", b =>
                {
                    b.HasOne("APromisedLand.Shared.DiberyTree.Models.UnitTree", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });
#pragma warning restore 612, 618
        }
    }
}
