// <auto-generated />
using APromisedLand.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APromisedLand.Api.Data.Migrations
{
    [DbContext(typeof(TreeDbContext))]
    partial class TreeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Models.CategoryTree", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CategoryTrees");

                    b.HasData(
                        new
                        {
                            Id = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            Description = "根分类示例",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample Root",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "39EA6315-0A74-40F6-A096-8E15CCC98579",
                            Description = "子分类 1",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 1",
                            ParentId = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "C1EBEE10-97F6-44C8-9852-2F574515BF51",
                            Description = "子分类 1.1",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 1.1",
                            ParentId = "39EA6315-0A74-40F6-A096-8E15CCC98579",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "C8969ED0-C018-4FDC-AE55-C363BD95C853",
                            Description = "子分类 2",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 2",
                            ParentId = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "ED0990CF-5BB7-4C36-A3BB-3AF606AD1974",
                            Description = "子分类 2.1",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 2.1",
                            ParentId = "C8969ED0-C018-4FDC-AE55-C363BD95C853",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "975599CC-B967-4AD2-B4B8-9E00D889FB4D",
                            Description = "子分类 2.2 [Archived]",
                            IsActive = false,
                            IsArchived = true,
                            Name = "Sample 2.2",
                            ParentId = "C8969ED0-C018-4FDC-AE55-C363BD95C853",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            Description = "子分类 3",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 3",
                            ParentId = "55705350-7071-43A4-AFAF-2F30B3CE2718",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "8E971C0E-B99A-4931-AFD6-46E44D6ECE5A",
                            Description = "子分类 3.1",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 3.1",
                            ParentId = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = "5C30BACA-3C11-4677-8123-8EC2BE729667",
                            Description = "子分类 3.2",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 3.2",
                            ParentId = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "1B16336D-FB7F-42AA-AFD2-F78388883336",
                            Description = "子分类 3.3",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 3.3",
                            ParentId = "27EE32B0-0F30-4331-AA85-61457B7A0912",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "35F02829-6490-467E-9D3E-C2EBF0EAA2B4",
                            Description = "子分类 3.3.1",
                            IsActive = true,
                            IsArchived = false,
                            Name = "Sample 3.3.1",
                            ParentId = "1B16336D-FB7F-42AA-AFD2-F78388883336",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Models.CategoryTree", b =>
                {
                    b.HasOne("APromisedLand.Shared.DiberyTree.Models.CategoryTree", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("APromisedLand.Shared.DiberyTree.Models.CategoryTree", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
