<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Elastic.Clients.Elasticsearch" Version="13.3.0" />
        <PackageReference Include="Aspire.Keycloak.Authentication" Version="13.4.6-preview.1.26319.6" />
        <PackageReference Include="Aspire.NATS.Net" Version="13.4.6" />
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.4.6" />
        <PackageReference Include="Aspire.StackExchange.Redis" Version="13.4.6" />
        <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.5.0" />
        <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="OllamaSharp" Version="5.4.30" />
        <PackageReference Include="Typesense" Version="8.5.0" />
        <PackageReference Include="WolverineFx.RabbitMQ" Version="6.24.5" />
        <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.24.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\APromisedLand.Shared\APromisedLand.Shared.csproj" />
      <ProjectReference Include="..\APromisedLand.Api\APromisedLand.Api.csproj" />
      <ProjectReference Include="..\APromisedLand.ServiceDefaults\APromisedLand.ServiceDefaults.csproj" />
    </ItemGroup>

</Project>
