@Keycloak_HostAddress = localhost:8080
@realm = apromisedland
@yarp_HttpHost = http://localhost:8088
@QuestionService_HostAddress = http://localhost:7001
@DevTunnel_Yarp = https://6fjddmjf-8090.jpe1.devtunnels.ms

POST https://{{Keycloak_HostAddress}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=diberysky&username=tian&password=Pa$$w0rd

> {%
    // 将 access_token 存入全局变量 token
    client.global.set("token", response.body.access_token);
%}


###

POST {{QuestionService_HostAddress}}/Questions/
Content-Type: application/json
Authorization: bearer {{token}}

{
  "title": "Next.js + SignalR 构建实时仪表板时如何管理连接状态？",
  "content": "我在 Next.js 项目中集成了 SignalR 客户端，但页面切换时连接会中断，且服务端渲染时无法建立连接。有没有推荐的架构模式来处理 SSR 和 WebSocket 的生命周期？",
  "tags": ["nextjs", "signalr", "typescript"]
}

> {%
    // 将 access_token 存入全局变量 token
    client.global.set("id", response.body.id);
%}
###
@id4=3b355463-e090-4ad8-918c-54d6f2fdff7d

PUT {{QuestionService_HostAddress}}/Questions/{{id4}}
Content-Type: application/json
Authorization: bearer {{token}}

{
  "title": "在Next.js 中使用 TypeScript 如何调用 Keycloak 鉴权 API？",
  "content": "目前我在 Next.js 项目中使用 next-auth 对接 Keycloak，但登录后无法获取用户角色信息。是否需要自定义 JWT 回调呢？请提供代码示例。",
  "tags": ["nextjs", "keycloak", "typescript"]
}

###
DELETE {{QuestionService_HostAddress}}/Question/{{id4}}
Content-Type: application/json
Authorization: bearer {{token}}

###
GET {{QuestionService_HostAddress}}/questions/{{id4}}
Accept: application/json

###

GET {{QuestionService_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: bearer {{token}}

###

GET {{QuestionService_HostAddress}}/tags/
Accept: application/json

###
GET {{DevTunnel_Yarp}}/questions/
Accept: application/json

###
GET {{DevTunnel_Yarp}}/tags/
Accept: application/json

