<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageReference Include="MudBlazor" Version="9.11.0" />
    <PackageReference Include="MudBlazor.Extensions" Version="9.11.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="TreeSky\TreeSky.razor.Action.cs">
      <DependentUpon>TreeSky.razor</DependentUpon>
    </Compile>
    <Compile Update="TreeSky\TreeSky.razor.Loading.cs">
      <DependentUpon>TreeSky.razor</DependentUpon>
    </Compile>
    <Compile Update="TreeSky\TreeSky.razor.Node.cs">
      <DependentUpon>TreeSky.razor</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TreeGraph.Shared\TreeGraph.Shared.csproj" />
  </ItemGroup>

</Project>
