<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageReference Include="MudBlazor" Version="9.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\APromisedLand.MauiBlazor\APromisedLand.MauiBlazor.csproj" />
    <ProjectReference Include="..\APromisedLand.Shared\APromisedLand.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DiberyTree\TreePage.razor.cs" />
    <Compile Remove="DiberyTree\Dialogs\CategoryTreeDialog.razor.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="DiberyTree\Dialogs\CategoryTreeDialog.razor" />
    <Content Remove="DiberyTree\Dialogs\CategoryTreeDeleteDialog.razor" />
    <Content Remove="DiberyTree\Dialogs\CategoryTreeSelectDialog.razor" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DiberyTree\Enums\" />
    <Folder Include="DiberyTree\Helpers\" />
    <Folder Include="DiberyTree\Interfaces\" />
    <Folder Include="DiberyTree\Models\" />
    <Folder Include="DiberyTree\Services\" />
  </ItemGroup>
  
</Project>
