<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageReference Include="MudBlazor" Version="9.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\APromisedLand.MauiBlazor\APromisedLand.MauiBlazor.csproj" />
    <ProjectReference Include="..\APromisedLand.Shared\APromisedLand.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DiberyTree\TreePage.razor.cs" />
    <Compile Remove="DiberyTree\Dialogs\CategoryTreeDialog.razor.cs" />
    <Compile Remove="Components\Dialogs\**" />
    <Compile Update="DiberyTree\Trees\TreeSky.razor.Action.cs">
      <DependentUpon>TreeSky.razor</DependentUpon>
    </Compile>
    <Compile Remove="DiberyTree\Category\CategoryTreeDialogPage.razor.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="DiberyTree\Dialogs\CategoryTreeDialog.razor" />
    <Content Remove="DiberyTree\Dialogs\CategoryTreeDeleteDialog.razor" />
    <Content Remove="DiberyTree\Dialogs\CategoryTreeSelectDialog.razor" />
    <Content Remove="Components\Dialogs\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DiberyTree\Helpers\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Components\Dialogs\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Components\Dialogs\**" />
  </ItemGroup>
  
</Project>
