<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\APromisedLand.Shared\APromisedLand.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MudBlazor" Version="9.8.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="DiberyTree\Services\AttributeApiClient.Definition.cs">
        <DependentUpon>AttributeApiClient.cs</DependentUpon>
      </Compile>
      <Compile Update="DiberyTree\Services\AttributeApiClient.Location.cs">
        <DependentUpon>AttributeApiClient.cs</DependentUpon>
      </Compile>
      <Compile Update="DiberyTree\Services\AttributeApiClient.Table.cs">
        <DependentUpon>AttributeApiClient.cs</DependentUpon>
      </Compile>
      <Compile Update="DiberyTree\Services\AttributeApiClient.Value.cs">
        <DependentUpon>AttributeApiClient.cs</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
