<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Elastic.Clients.Elasticsearch" Version="13.3.0" />
        <PackageReference Include="Aspire.NATS.Net" Version="13.5.2" />
        <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.5.0" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
        <PackageReference Include="OllamaSharp" Version="5.4.30" />
        <PackageReference Include="Typesense" Version="8.5.0" />
        <PackageReference Include="Zafiro.FileSystem.SeaweedFS" Version="47.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\APromisedLand.Shared\APromisedLand.Shared.csproj" />
    </ItemGroup>

</Project>